#Task 1

Write a class called Customer with the required constructor and methods to get the
following output.

Subtasks:
1. Create a class called Customer.
2. Create the required constructor.
3. Create a method called greet that works if no arguments are passed or if one
argument is passed. (Hint: You may need to use the keyword NONE)
4. Create a method called purchase that can take as many arguments as the user
wants to give.

[You are not allowed to change the code below]

# Write your codes for subtasks 1-4 here.

customer_1 = Customer("Sam")

customer_1.greet()

customer_1.purchase("chips", "chocolate", "orange juice")

print("-----------------------------")

customer_2 = Customer("David")

customer_2.greet("David")

customer_2.purchase("orange juice")

OUTPUT:

Hello!

Sam, you purchased 3 item(s):

chips

chocolate

orange juice

-----------------------------

Hello David! 

David, you purchased 1 item(s):

orange juice

In [ ]:
class Customer:
   def __init__(self,name):
     self.name=name

   def greet(self,name=None):
     if name!=None:
        self.name=name
        print(f'Hello {self.name}!')
     else:
      print('Hello!')
    
   def purchase(self,*items):
      self.items=items
      total_items=len(self.items)
      print(f'{self.name},you purchased {total_items} item(s):')
      for i in self.items:
        print(i)

customer_1 = Customer("Sam")
customer_1.greet()
customer_1.purchase("chips", "chocolate", "orange juice")
print("-----------------------------")
customer_2 = Customer("David")
customer_2.greet("David")
customer_2.purchase("orange juice")

Hello!
Sam,you purchased 3 item(s):
chips
chocolate
orange juice
-----------------------------
Hello David!
David,you purchased 1 item(s):
orange juice

#Task 2

The Giant Panda Protection and Research Center in the Sichuan province of southwest
China, actually employs a category of workers known as panda nannies. The primary
responsibility is to play with adorable panda cubs and name them, determine gender,
keep track of their age and hours they sleep. So being a programmer panda nanny, you
will create a code that will do all these works for you.
1. Create a class named Panda and also write the constructor.
2. Access the instance attributes and print them in the given format.
3. Call instance methods to keep track of their daily hours of sleep.
4. Suppose consulting with other panda nannies you have set some criteria based
on which you will make their diet plans. The criteria are:

    ** Mixed Veggies for pandas having 3 to 5 hours (included) of sleep daily.

    ** Eggplant & Tofu for pandas having 6 to 8 hours (included) of sleep daily.

    ** Broccoli Chicken for pandas having 9 to 11 hours (included) of sleep   daily.

    ** Lastly if no arguments are passed then just give it bamboo leaves.

Now handle this problem modifying the method designed to keep track of their daily
hours of sleep and determine diet plan using method overloading.

[You are not allowed to change the code below]

#Write your code here for subtasks 1-4.

panda1 = Panda("Kunfu","Male", 5)

panda2=Panda("Pan Pan","Female",3)

panda3=Panda("Ming Ming","Female",8)

print("{} is a {} Panda Bear who is {} years
old".format(panda1.name,panda1.gender,panda1.age))

print("{} is a {} Panda Bear who is {} years
old".format(panda2.name,panda2.gender,panda2.age))

print("{} is a {} Panda Bear who is {} years
old".format(panda3.name,panda3.gender,panda3.age))

print("===========================")

print(panda2.sleep(10))

print(panda1.sleep(4))

print(panda3.sleep())

OUTPUT:

Kunfu is a Male Panda Bear who is 5 years
old

Pan Pan is a Female Panda Bear who is 3
years old

Ming Ming is a Female Panda Bear who is 8
years old

===========================

Pan Pan sleeps 10 hours daily and should
have Broccoli Chicken

Kunfu sleeps 4 hours daily and should have
Mixed Veggies

Ming Ming's duration is unknown thus should
have only bamboo leaves

In [ ]:
class Panda:
  def __init__(self,name,gender,age):
    self.name=name
    self.gender=gender
    self.age=age

  def sleep(self,hour=None):
    self.hour=hour
    if self.hour==None:
      return f"{self.name}'s duration is unknown thus should have only bamboo leaves"
    elif 3<=hour<=5:
      return f'{self.name} sleeps {self.hour} hours daily and should have Mixed Veggies'
    elif 6<=hour<=8:
      return f'{self.name} sleeps {self.hour} hours daily and should have  Eggplant & Tofu'
    elif 9<=hour<=11:
       return f'{self.name} sleeps {self.hour} hours daily and should have Broccoli Chicken'
    

  
  
panda1 = Panda("Kunfu","Male", 5)
panda2=Panda("Pan Pan","Female",3)
panda3=Panda("Ming Ming","Female",8)
print("{} is a {} Panda Bear who is {} years old".format(panda1.name,panda1.gender,panda1.age))
print("{} is a {} Panda Bear who is {} years old".format(panda2.name,panda2.gender,panda2.age))
print("{} is a {} Panda Bear who is {} years old".format(panda3.name,panda3.gender,panda3.age))
print("===========================")
print(panda2.sleep(10))
print(panda1.sleep(4))
print(panda3.sleep())

Kunfu is a Male Panda Bear who is 5 years old
Pan Pan is a Female Panda Bear who is 3 years old
Ming Ming is a Female Panda Bear who is 8 years old
===========================
Pan Pan sleeps 10 hours daily and should have Broccoli Chicken
Kunfu sleeps 4 hours daily and should have Mixed Veggies
Ming Ming's duration is unknown thus should have only bamboo leaves

#Task 3

Analyze the given code below to write Cat class to get the output as shown.
Hints:
• Remember, the constructor is a special method. Here, you have to deal with
constructor overloading which is similar to method overloading.
• You may need to use the keyword None
• Your class should have 2 variables
[You are not allowed to change the code below]

#Write your code here

c1 = Cat()

c2 = Cat("Black")

c3 = Cat("Brown", "jumping")

c4 = Cat("Red", "purring")

c1.printCat()

c2.printCat()

c3.printCat()

c4.printCat()

c1.changeColor("Blue")

c3.changeColor("Purple")

c1.printCat()

c3.printCat()

OUTPUT

White cat is sitting

Black cat is sitting

Brown cat is jumping

Red cat is purring

Blue cat is sitting

Purple cat is jumping

In [ ]:
class Cat:
  def  __init__(self,color='White',action='sitting'):
    self.color=color
    self.action=action

  def printCat(self):
    print(f'{self.color} cat is {self.action}')

  def changeColor(self,new_color):
    self.color=new_color
c1 = Cat()
c2 = Cat("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()

White cat is sitting
Black cat is sitting
Brown cat is jumping
Red cat is purring
Blue cat is sitting
Purple cat is jumping

#Task 4

Implement the design of the Student class so that the following output is produced:

Driver Code Output

# Write your code here

s1 = Student()

s1.quizcalc(10)

print('--------------------------------')

s1.printdetail()

s2 = Student('Harry')

s2.quizcalc(10,8)

print('--------------------------------')

s2.printdetail()

s3 = Student('Hermione')

s3.quizcalc(10,9,10)

print('--------------------------------')

s3.printdetail()

--------------------------------

Hello default student

Your average quiz score is 3.3333333333333335

--------------------------------

Hello Harry

Your average quiz score is 6.0

--------------------------------

Hello Hermione

Your average quiz score is 9.666666666666666

In [ ]:
class Student:
  def __init__(self,name=None):
    self.name=name
    
  def quizcalc(self,*score):
    self.score=score
    sum=0
    for i in self.score:
      sum+=i
    self.num=sum/3

  def printdetail(self):
    if self.name==None:
      print('Hello default student')
    else:
      print('Hello',self.name)

    print('Your average quiz score is',self.num)

s1 = Student()
s1.quizcalc(10)
print('--------------------------------')
s1.printdetail()
s2 = Student('Harry')
s2.quizcalc(10,8)
print('--------------------------------')
s2.printdetail()
s3 = Student('Hermione')
s3.quizcalc(10,9,10)
print('--------------------------------')
s3.printdetail()

--------------------------------
Hello default student
Your average quiz score is 3.3333333333333335
--------------------------------
Hello Harry
Your average quiz score is 6.0
--------------------------------
Hello Hermione
Your average quiz score is 9.666666666666666

# Task 5

Design the Student class such a way so that the following code provides the expected
output.

Hint:

• Write the constructor with appropriate default value for arguments.

• Write the dailyEffort() method with appropriate argument.

• Write the prinDetails() method. For printing suggestions check the following
instructions.

➢ If hour <= 2 print 'Suggestion: Should give more effort!'

➢ If hour <= 4 print 'Suggestion: Keep up the good work!'

➢ Else print 'Suggestion: Excellent! Now motivate others.'

[You are not allowed to change the code below]

# Write your code here.

harry = Student('Harry Potter', 123)

harry.dailyEffort(3)

harry.printDetails()

print('========================')

john = Student("John Wick", 456, "BBA")

john.dailyEffort(2)

john.printDetails()

print('========================')

naruto = Student("Naruto Uzumaki", 777, "Ninja")

naruto.dailyEffort(6)

naruto.printDetails()

OUTPUT:

Name: Harry Potter

ID: 123

Department: CSE

Daily Effort: 3 hour(s)

Suggestion: Keep up the good work!

========================

Name: John Wick

ID: 456

Department: BBA

Daily Effort: 2 hour(s)

Suggestion: Should give more effort!

========================

Name: Naruto Uzumaki

ID: 777

Department: Ninja

Daily Effort: 6 hour(s)

Suggestion: Excellent! Now motivate others.

In [ ]:
class Student:
    def __init__(self,name,id,dept='CSE'):
      self.name=name
      self.id=id
      self.dept=dept
    def dailyEffort(self,hour):
      self.hour=hour

    def printDetails(self):
      print('Name:',self.name)
      print('ID:',self.id)
      print('Department:',self.dept)
      print('Daily Effort:',self.hour,'hour(s)')
      if self.hour<= 2:
        print('Suggestion: Should give more effort!')
      elif self.hour<=4    :
        print('Suggestion: Keep up the good work!')
      else:
        print('Suggestion: Excellent! Now motivate others.')


harry = Student('Harry Potter', 123)
harry.dailyEffort(3)
harry.printDetails()
print('========================')
john = Student("John Wick", 456, "BBA")
john.dailyEffort(2)
john.printDetails()
print('========================')
naruto = Student("Naruto Uzumaki", 777, "Ninja")
naruto.dailyEffort(6)
naruto.printDetails()

Name: Harry Potter
ID: 123
Department: CSE
Daily Effort: 3 hour(s)
Suggestion: Keep up the good work!
========================
Name: John Wick
ID: 456
Department: BBA
Daily Effort: 2 hour(s)
Suggestion: Should give more effort!
========================
Name: Naruto Uzumaki
ID: 777
Department: Ninja
Daily Effort: 6 hour(s)
Suggestion: Excellent! Now motivate others.

# Task 6

Implement the design of the Patient class so that the following output is produced:

[You are not allowed to change the code below]

# Write your code here.

p1 = Patient(“Thomas”, 23)

p1.add_Symptom(“Headache”)

p2 = Patient(“Carol”, 20)

p2.add_Symptom(“Vomiting”, “Coughing”)

p3 = Patient(“Mike”, 25)

p3.add_Symptom(“Fever”, “Headache”, “Coughing”)

print("=========================")

p1.printPatientDetail()

print("=========================")

p2.printPatientDetail()

print("=========================")

p3.printPatientDetail()

OUTPUT:

=========================

Name: Thomas

Age: 23

Symptoms: Headache

=========================

Name: Carol

Age: 20

Symptoms: Vomiting, Coughing

=========================

Name: Mike

Age: 25

Symptoms: Fever, Headache, Coughing

In [ ]:
class Patient:
  def __init__(self,name,age):
    self.name=name
    self.age=age
  def add_Symptom(self,*sym):
    self.sym=sym 
  def printPatientDetail(self):
    print('Name:',self.name)
    print('Age:',self.age)
    print('Symptoms:',end='')
    for i in range(len(self.sym)):
      if i!=(len(self.sym)-1):
        print(self.sym[i],end=',')
      else:
        print(self.sym[i])

p1 = Patient('Thomas', 23)
p1.add_Symptom('Headache')
p2 = Patient('Carol', 20)
p2.add_Symptom('Vomiting', 'Coughing')
p3 = Patient('Mike', 25)
p3.add_Symptom('Fever', 'Headache', 'Coughing')
print("=========================")
p1.printPatientDetail()
print("=========================")
p2.printPatientDetail()
print("=========================")
p3.printPatientDetail()

=========================
Name: Thomas
Age: 23
Symptoms:Headache
=========================
Name: Carol
Age: 20
Symptoms:Vomiting,Coughing
=========================
Name: Mike
Age: 25
Symptoms:Fever,Headache,Coughing

# Task 7

Design the Match class such a way so that the following code provides the expected

# Write your code here.

match1 = Match("Rangpur Riders-Cumilla Victorians")

print("=========================")

match1.add_run(4)

match1.add_run(6)

match1.add_over(1)

print(match1.print_scoreboard())

print("=========================")

match1.add_over(5)

print("=========================")

match1.add_wicket(1)

print(match1.print_scoreboard())

OUTPUT:

5..4..3..2..1.. Play !!!

============================

Batting Team: Rangpur Riders

Bowling Team: Cumilla Victorians

Total Runs: 10 Wickets: 0 Overs: 1

============================

Warning! Cannot add 5 over/s (5 over match)

============================

Batting Team: Rangpur Riders

Bowling Team: Cumilla Victorians

Total Runs: 10 Wickets: 1 Overs: 1

In [ ]:
class Match:
  def __init__(self,teams):
    self.teams=teams.split('-')
    print('5..4..3..2..1.. Play !!!')
    self.total_runs=0
    self.total_over=0
    self.wickets=0

  def add_run(self,run):
    self.run=run
    self.total_runs+=self.run
  def add_over(self,over):
    self.over=over
    if self.over+self.total_over<=5:
            self.total_over+=self.over
    else:
            print(f'Warning! Cannot add {self.over} over/s (5 over match)')
  def add_wicket(self,wicket):
    self.wicket=wicket
    self.wickets+=self.wicket
  def print_scoreboard(self):
    return f'Batting Team: {self.teams[0]}\nBowling Team: {self.teams[1]}\nTotal Runs:{self.total_runs} Wickets:{self.wickets} Overs:{self.total_over}'
 



  

match1 = Match("Rangpur Riders-Cumilla Victorians")
print("=========================")
match1.add_run(4)
match1.add_run(6)
match1.add_over(1)
print(match1.print_scoreboard())
print("=========================")
match1.add_over(5)
print("=========================")
match1.add_wicket(1)
print(match1.print_scoreboard())

5..4..3..2..1.. Play !!!
=========================
Batting Team: Rangpur Riders
Bowling Team: Cumilla Victorians
Total Runs:10 Wickets:0 Overs:1
=========================
Warning! Cannot add 5 over/s (5 over match)
=========================
Batting Team: Rangpur Riders
Bowling Team: Cumilla Victorians
Total Runs:10 Wickets:1 Overs:1

# Task 8

Design the ParcelKoro class such a way so that the following code provides the expected
output.

Hint: total_fee = (total_weight * 20) + location_charge.

Note: For the method calculate fee: if the delivery location is not given, the
location_charge will be 50 taka or else 100 taka. Also, while calculating total fee, if the
product weight is 0 the total_fee should also be 0.

Assume only these 3 ways you can create an object of a class.

[You are not allowed to change the code below]

# Write your code here.

print("**********************")

p1 = ParcelKoro()

p1.calculateFee()

p1.printDetails()

print("**********************")

p2 = ParcelKoro('Bob The Builder')

p2.calculateFee()

p2.printDetails()

print("----------------------------")

p2.product_weight = 15

p2.calculateFee()

p2.printDetails()

print("**********************")

p3 = ParcelKoro('Dora The Explorer', 10)

p3.calculateFee('Dhanmondi')

p3.printDetails()

OUTPUT:

**********************

Customer Name: No name set

Product Weight: 0

Total fee: 0

**********************

Customer Name: Bob The Builder

Product Weight: 0

Total fee: 0

----------------------------

Customer Name: Bob The Builder

Product Weight: 15

Total fee: 350

**********************

Customer Name: Dora The Explorer

Product Weight: 10

Total fee: 300

In [ ]:
class ParcelKoro:
  def __init__(self,name=None,weight=None):
    self.name=name
    if weight==None:
      self.product_weight=0
    else:
      self.product_weight=weight
  def calculateFee(self,loc=None):
    self.loc=loc
    if self.product_weight==0:
       self.fee=0
    elif self.loc==None:
       self.fee=(self.product_weight*20)+50
    else:
       self.fee=(self.product_weight*20)+100
      
  def printDetails(self):
    if self.name==None:
       print('Customer Name: No name set')
    else:
      print('Customer Name:',self.name)

    print('Product Weight:',self.product_weight)
    print('Total fee:',self.fee)
print("**********************")
p1 = ParcelKoro()
p1.calculateFee()
p1.printDetails()
print("**********************")
p2 = ParcelKoro('Bob The Builder')
p2.calculateFee()
p2.printDetails()
print("----------------------------")
p2.product_weight = 15
p2.calculateFee()
p2.printDetails()
print("**********************")
p3 =ParcelKoro('Dora The Explorer', 10)
p3.calculateFee('Dhanmondi')
p3.printDetails()

**********************
Customer Name: No name set
Product Weight: 0
Total fee: 0
**********************
Customer Name: Bob The Builder
Product Weight: 0
Total fee: 0
----------------------------
Customer Name: Bob The Builder
Product Weight: 15
Total fee: 350
**********************
Customer Name: Dora The Explorer
Product Weight: 10
Total fee: 300

# Task 9
Implement the design of the Batsman class so that the following output is produced:
Hint: Batting strike rate (s/r) = runsScored / ballsFaced x 100.
Driver Code
Output
# Write your code here
b1 = Batsman(6101, 7380)

b1.printCareerStatistics()

print("============================")

b2 = Batsman("Liton Das", 678, 773)

b2.printCareerStatistics()

print("----------------------------")

print(b2.battingStrikeRate())

print("============================")

b1.setName("Shakib Al Hasan")

b1.printCareerStatistics()

print("----------------------------")

print(b1.battingStrikeRate())

#Output:

Name: New Batsman 

Runs Scored: 6101 , Balls Faced: 7380 ============================

 Name: Liton Das 

 Runs Scored: 678 , Balls Faced: 773 

 ----------------------------

  87.71021992238033 

  ============================ 

  Name: Shakib Al Hasan 

  Runs Scored: 6101 , Balls Faced: 7380 

  ----------------------------
   82.66937669376694

In [ ]:
class Batsman:
  def __init__(self,*info):
    self.info=info
    if len(self.info)==3:
          self.name=self.info[0]
          self.runs=self.info[1]
          self.balls=self.info[2]

    else:
          self.name='New Batsman'
          self.runs=self.info[0]
          self.balls=self.info[1]

  def setName(self,name):
    self.name=name

  def printCareerStatistics(self):
    print('Name:',self.name)
    print('Runs Scored:',self.runs,', Balls Faced:',self.balls)
  
  def battingStrikeRate(self):
    strike=(self.runs/self.balls)*100
    return strike

b1 = Batsman(6101, 7380)
b1.printCareerStatistics()
print("============================")
b2 = Batsman("Liton Das", 678, 773)
b2.printCareerStatistics()
print("----------------------------")
print(b2.battingStrikeRate())
print("============================")
b1.setName("Shakib Al Hasan")
b1.printCareerStatistics()
print("----------------------------")
print(b1.battingStrikeRate())

Name: New Batsman
Runs Scored: 6101 , Balls Faced: 7380
============================
Name: Liton Das
Runs Scored: 678 , Balls Faced: 773
----------------------------
87.71021992238033
============================
Name: Shakib Al Hasan
Runs Scored: 6101 , Balls Faced: 7380
----------------------------
82.66937669376694

# Task 10
Implement the design of the EPL_Team class so that the following output is produced:
Driver Code
Output
# Write your code here

manu = EPL_Team('Manchester United', 'Glory Glory Man United') 

chelsea = EPL_Team('Chelsea') 

print('===================') 

print(manu.showClubInfo())

print('##################') 

manu.increaseTitle() 

print(manu.showClubInfo()) 

print('===================') 

print(chelsea.showClubInfo()) 

chelsea.changeSong('Keep the blue flag flying high') 

print(chelsea.showClubInfo()) 

#Output:

=================== 

Name: Manchester United 

Song: Glory Glory Man United Total 

No of title: 0 

##################

 Name: Manchester United 

 Song: Glory Glory Man United 

 Total No of title: 1 

 ===================

Name: Chelsea 

Song: No Slogan Total 

No of title: 0 

Name: Chelsea 

Song: Keep the blue flag flying high 

Total No of title: 0

In [ ]:
class EPL_Team:
  def __init__(self,team,song='No Slogan'):
    self.team=team
    self.song=song
    self.title=0
  def showClubInfo(self):
     return f'Name: {self.team}\nSong: {self.song}\nTotal No of title: {self.title}'

  def increaseTitle(self):
    self.title+=1
  def changeSong(self,new_song):
    self.song=new_song
 



manu = EPL_Team('Manchester United', 'Glory Glory Man United') 
chelsea = EPL_Team('Chelsea') 
print('===================') 
print(manu.showClubInfo())
print('##################') 
manu.increaseTitle() 
print(manu.showClubInfo()) 
print('===================') 
print(chelsea.showClubInfo()) 
chelsea.changeSong('Keep the blue flag flying high') 
print(chelsea.showClubInfo())

===================
Name: Manchester United
Song: Glory Glory Man United
Total No of title: 0
##################
Name: Manchester United
Song: Glory Glory Man United
Total No of title: 1
===================
Name: Chelsea
Song: No Slogan
Total No of title: 0
Name: Chelsea
Song: Keep the blue flag flying high
Total No of title: 0

# Task 11
Implement the design of the Author class so that the following output is produced:

Driver Code Output

# Write your code here

auth1 = Author('Humayun Ahmed')

auth1.addBooks('Deyal', 'Megher Opor Bari')

auth1.printDetails()

print(‘===================’)

auth2 = Author()

print(auth2.name)

auth2.changeName('Mario Puzo')

auth2.addBooks('The Godfather', 'Omerta', 'The Sicilian')

print(‘===================’)

auth2.printDetails()

print(‘===================’)

auth3 = Author('Paolo Coelho', 'The Alchemist', 'The Fifth Mountain')

auth3.printDetails()

Author Name: Humayun Ahmed

--------

List of Books:

Deyal

Megher Opor Bari

===================

Default

===================

Author Name: Mario Puzo

--------

List of Books:

The Godfather

Omerta

The Sicilian

===================

Author Name: Paolo Coelho

--------

List of Books:

The Alchemist

The Fifth Mountain

In [ ]:
class Author:
  def __init__(self,*info):
    self.info=info
    if len(self.info)==0:
      self.name='Default'
    else:
      self.name=self.info[0]

    self.book=[]
    for i in range(1,len(self.info)):
       self.book.append(self.info[i])

  def addBooks(self,*new_books):
    self.new_books=new_books
    for i in self.new_books:
      self.book.append(i)
  def changeName(self,new_name):
    self.name=new_name

  def printDetails(self):
    print('Author Name:',self.name)
    print('--------')
    print('List of Books:')
    for i in self.book:
      print(i)

    

auth1 = Author('Humayun Ahmed')
auth1.addBooks('Deyal', 'Megher Opor Bari')
auth1.printDetails()
print('===================')
auth2 = Author()
print(auth2.name)
auth2.changeName('Mario Puzo')
auth2.addBooks('The Godfather', 'Omerta', 'The Sicilian')
print('===================')
auth2.printDetails()
print('===================')
auth3 = Author('Paolo Coelho', 'The Alchemist', 'The Fifth Mountain')
auth3.printDetails()

Author Name: Humayun Ahmed
--------
List of Books:
Deyal
Megher Opor Bari
===================
Default
===================
Author Name: Mario Puzo
--------
List of Books:
The Godfather
Omerta
The Sicilian
===================
Author Name: Paolo Coelho
--------
List of Books:
The Alchemist
The Fifth Mountain

# Task 12
Using TaxiLagbe apps, users can share a single taxi with multiple people.
Implement the design of the TaxiLagbe class so that the following output is produced:
Hint:
1. Each taxi can carry maximum 4 passengers
2. addPassenger() method takes the last name of the passenger and ticket fare for that person in an underscore (-) separated string.
Driver Code

# Write your code here

# Do not change the following lines of code.

taxi1 = TaxiLagbe('1010-01', 'Dhaka')

print('-------------------------------')

taxi1.addPassenger('Walker_100', 'Wood_200')

taxi1.addPassenger('Matt_100')

taxi1.addPassenger('Wilson_105')

print('-------------------------------')

taxi1.printDetails()

print('-------------------------------')

taxi1.addPassenger('Karen_200')

print('-------------------------------')

taxi1.printDetails()

print('-------------------------------')

taxi2 = TaxiLagbe('1010-02', 'Khulna')

taxi2.addPassenger('Ronald_115')

taxi2.addPassenger('Parker_215')

print('-------------------------------')

taxi2.printDetails() 

-------------------------------------- 

Dear Walker! Welcome to TaxiLagbe. Dear Wood! Welcome to TaxiLagbe. Dear Matt! Welcome to TaxiLagbe. Dear Wilson! Welcome to TaxiLagbe. 

-------------------------------------- 

Trip info for Taxi number: 1010-01 This taxi can cover only Dhaka area. Total passengers: 4 Passenger lists: Walker, Wood, Matt, Wilson Total collected fare: 505 Taka 

-------------------------------------- 

Taxi Full! No more passengers can be added. 

-------------------------------------- 

Trip info for Taxi number: 1010-01 This taxi can cover only Dhaka area. Total passengers: 4 Passenger lists: Walker, Wood, Matt, Wilson Total collected fare: 505 Taka 

-------------------------------------- 

Dear Ronald! Welcome to TaxiLagbe. Dear Parker! Welcome to TaxiLagbe. 

-------------------------------------- 

Trip info for Taxi number: 1010-02 This taxi can cover only Khulna area. Total passengers: 2 Passenger lists: Ronald, Parker Total collected fare: 330 Taka

In [ ]:
class TaxiLagbe:
  def __init__(self,taxi,loc):
    self.taxi=taxi
    self.loc=loc
    self.passenger=[]

  def addPassenger(self,*passenger):
    for i in passenger:
      word=''
      for j in range(len(i)):
        if i[j]!='_':
          word+=i[j]
        else:
          break

      if len(self.passenger)!=4:
        self.passenger.append(i)
        print(f'Dear {word}! Welcome to TaxiLagbe.')
      else:
        print('Taxi Full! No more passengers can be added.')

  def printDetails(self):
    passenger_name=[]
    fare=[]
    total_fare=0
    for i in self.passenger:
       info=i.split('_')
       passenger_name.append(info[0])
       fare.append(int(info[1]))
  
    for i in fare:
      total_fare+=i

    print('Trip info for Taxi number:',self.taxi)
    print('This taxi can cover only',self.loc,'area.')
    print('Total passengers:',len(self.passenger))
    print('passenger lists:')
    for i in range(len(passenger_name)):
      if i!=len(passenger_name)-1:
        print(passenger_name[i],end=',')
      else:
        print(passenger_name[i])
    print('Total collected fare:',total_fare,'Taka')



taxi1 = TaxiLagbe('1010-01', 'Dhaka')
print('-------------------------------')
taxi1.addPassenger('Walker_100', 'Wood_200')
taxi1.addPassenger('Matt_100')
taxi1.addPassenger('Wilson_105')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi1.addPassenger('Karen_200')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi2 = TaxiLagbe('1010-02', 'Khulna')
taxi2.addPassenger('Ronald_115')
taxi2.addPassenger('Parker_215')
print('-------------------------------')
taxi2.printDetails()

-------------------------------
Dear Walker! Welcome to TaxiLagbe.
Dear Wood! Welcome to TaxiLagbe.
Dear Matt! Welcome to TaxiLagbe.
Dear Wilson! Welcome to TaxiLagbe.
-------------------------------
Trip info for Taxi number: 1010-01
This taxi can cover only Dhaka area.
Total passengers: 4
passenger lists:
Walker,Wood,Matt,Wilson
Total collected fare: 505 Taka
-------------------------------
Taxi Full! No more passengers can be added.
-------------------------------
Trip info for Taxi number: 1010-01
This taxi can cover only Dhaka area.
Total passengers: 4
passenger lists:
Walker,Wood,Matt,Wilson
Total collected fare: 505 Taka
-------------------------------
Dear Ronald! Welcome to TaxiLagbe.
Dear Parker! Welcome to TaxiLagbe.
-------------------------------
Trip info for Taxi number: 1010-02
This taxi can cover only Khulna area.
Total passengers: 2
passenger lists:
Ronald,Parker
Total collected fare: 330 Taka

# Task 13

Implement the design of the Account class so that the following output is produced:

Driver Code Output

# Write your code here

a1 = Account()

print(a1.details())

print("------------------------")

a1.name = "Oliver"

a1.balance = 10000.0

print(a1.details())

print("------------------------")

a2 = Account("Liam")

print(a2.details())

print("------------------------")

a3 = Account("Noah",400)

print(a3.details())

print("------------------------")

a1.withdraw(6930)

print("------------------------")

a2.withdraw(600)

print("------------------------")

a1.withdraw(6929)

Default Account

0.0

------------------------

Oliver

10000.0

------------------------

Liam

0.0

------------------------

Noah

400.0

------------------------

Sorry, Withdraw unsuccessful! The account
balance after deducting withdraw amount is
equal to or less than minimum.

------------------------

Sorry, Withdraw unsuccessful! The account
balance after deducting withdraw amount is
equal to or less than minimum.

------------------------

Withdraw successful! New balance is: 3071.0

In [ ]:
class Account:
  def __init__(self,name='Default Account',balance=0.0):
    self.name=name
    self.balance=balance

  def details(self):
    return f'{self.name} \n{self.balance}'

  def withdraw(self,money):
    self.money=money
    if self.balance-self.money>=3071:
      self.balance=self.balance-self.money
      print('Withdraw successful! New balance is:',self.balance)
    else:
      print('Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.')


  

a1 = Account()
print(a1.details())
print("------------------------")
a1.name = "Oliver"
a1.balance = 10000.0
print(a1.details())
print("------------------------")
a2 = Account("Liam")
print(a2.details())
print("------------------------")
a3 = Account("Noah",400)
print(a3.details())
print("------------------------")
a1.withdraw(6930)
print("------------------------")
a2.withdraw(600)
print("------------------------")
a1.withdraw(6929)

Default Account
0.0
------------------------
Oliver
10000.0
------------------------
Liam
0.0
------------------------
Noah
400
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.
------------------------
Withdraw successful! New balance is: 3071.0

# Task 14
Implement the design of the StudentDatabase class so that the following output is produced:
GPA = Sum of (Grade Points * Credits)/ Credits attempted

# Write your code here

# Do not change the following lines of code.

s1 = StudentDatabase('Pietro', '10101222')

s1.calculateGPA(['CSE230: 4.0', 'CSE220: 4.0', 'MAT110: 4.0'], 'Summer2020')

s1.calculateGPA(['CSE250: 3.7', 'CSE330: 4.0'], 'Summer2021')
print(f'Grades for {s1.name}\n{s1.grades}')

print('------------------------------------------------------')

s1.printDetails()

s2 = StudentDatabase('Wanda', '10103332')

s2.calculateGPA(['CSE111: 3.7', 'CSE260: 3.7', 'ENG101: 4.0'], 'Summer2022')

print('------------------------------------------------------')

print(f'Grades for {s2.name}\n{s2.grades}')

print('------------------------------------------------------')

s2.printDetails() 

Grades for Pietro 
{'Summer2020': {('CSE230', 'CSE220', 'MAT110'): 4.0}, 'Summer2021': {('CSE250', 'CSE330'): 3.85}} 

----------------------------------------------- 
Name: Pietro
ID: 10101222 
Courses taken in Summer2020: 
CSE230 
CSE220 
MAT110 
GPA: 4.0 
Courses taken in Summer2021: 
CSE250 
CSE330 
GPA: 3.85 

----------------------------------------------- 
Grades for Wanda 
{'Summer2022': {('CSE111', 'CSE260', 'ENG101'): 3.8}} 

----------------------------------------------- 
Name: Wanda 
ID: 10103332 
Courses taken in Summer2022:
CSE111 
CSE260 
ENG101 
GPA: 3.8

In [ ]:
class StudentDatabase:
  def __init__(self,name,id):
    self.name=name
    self.id=id
    self.grades={}
  def calculateGPA(self,details,sem):
    sem_GPA={}
    course_list=[]
    totalGPA=0
    for info in details:
      name,grade=info.split(':')
      course_list.append(name)
      totalGPA+=float(grade)
    sem_GPA[tuple(course_list)]  =totalGPA/len(course_list)
    self.grades[sem]=sem_GPA

  def printDetails(self):
    print('Name:',self.name)
    print('ID:',self.id)
    for key,value in self.grades.items():
      print(f'Courses taken in {key}:')
      for courses,GPA in value.items():
        for course in courses:
          print(course)
        print('GPA:',round(GPA,3))

s1 = StudentDatabase('Pietro', '10101222')
s1.calculateGPA(['CSE230: 4.0', 'CSE220: 4.0', 'MAT110: 4.0'], 'Summer2020')
s1.calculateGPA(['CSE250: 3.7', 'CSE330: 4.0'], 'Summer2021')
print(f'Grades for {s1.name}\n{s1.grades}')
print('------------------------------------------------------')
s1.printDetails()
s2 = StudentDatabase('Wanda', '10103332')
s2.calculateGPA(['CSE111: 3.7', 'CSE260: 3.7', 'ENG101: 4.0'], 'Summer2022')
print('------------------------------------------------------')
print(f'Grades for {s2.name}\n{s2.grades}')
print('------------------------------------------------------')
s2.printDetails()

Grades for Pietro
{'Summer2020': {('CSE230', 'CSE220', 'MAT110'): 4.0}, 'Summer2021': {('CSE250', 'CSE330'): 3.85}}
------------------------------------------------------
Name: Pietro
ID: 10101222
Courses taken in Summer2020:
CSE230
CSE220
MAT110
GPA: 4.0
Courses taken in Summer2021:
CSE250
CSE330
GPA: 3.85
------------------------------------------------------
Grades for Wanda
{'Summer2022': {('CSE111', 'CSE260', 'ENG101'): 3.8000000000000003}}
------------------------------------------------------
Name: Wanda
ID: 10103332
Courses taken in Summer2022:
CSE111
CSE260
ENG101
GPA: 3.8

#ungraded

#Task 20
Design a Student class so that the following output is produced upon executing the
following code

Driver Code Output

# Write your code here
# Do not change the following lines of code.
s1 = Student()

print(“=========================”)

s2 = Student(“Carol”)

print(“=========================”)

s3 = Student(“Jon”, “EEE”)

print(“=========================”)

s1.update_name(“Bob”)

s1.update_department(“CSE”)

s2.update_department(“BBA”)

s1.enroll(“CSE110”, “MAT110”, “ENG091”)

s2.enroll(“BUS101”)

s3.enroll(“MAT110”, “PHY111”)

print(“###########################”)

s1.printDetail()

print(“=========================”)

s2.printDetail()

print(“=========================”)

s3.printDetail()

Student name and department need to be set

Department for Carol needs to be set

Jon is from EEE department

###########################

Name: Bob

Department: CSE

Bob enrolled in 3 course(s):

CSE110, MAT110, ENG091

=========================

Name: Carol

Department: BBA

Carol enrolled in 1 course(s):

BUS101

=========================

Name: Jon

Department: EEE

Jon enrolled in 2 course(s):

MAT110, PHY111

In [ ]:
class Student:
  def __init__(self,name=None,dept=None):
      if name==None and dept==None:
        print('Student name and department need to be set')
      elif name==None:
        print('Name needs to be set')
        self.dept=dept
      elif dept==None:
        self.name=name
        print('Department for Carol needs to be set')
      else:
        self.name=name
        self.dept=dept
        print(f'{self.name} is from {self.dept} department')
  def update_name(self,name):
      self.name=name
  def update_department(self,dept):
      self.dept=dept
  def enroll(self,*course):
    self.course=course
  def printDetail(self):
    print('Name:',self.name)
    print('Department:',self.dept)
    print(self.name,'enrolled in',len(self.course),'course(s):')
    for i in self.course:
      if self.course.index(i)!=len(self.course)-1:
        print(i,end=',')
      else:
        print(i)
  
s1 = Student()
print('=========================')
s2 = Student('Carol')
print('=========================')
s3 = Student('Jon', 'EEE')
print('=========================')
s1.update_name('Bob')
s1.update_department('CSE')
s2.update_department('BBA')
s1.enroll('CSE110', 'MAT110', 'ENG091')
s2.enroll('BUS101')
s3.enroll('MAT110', 'PHY111')
print('###########################')
s1.printDetail()
print('=========================')
s2.printDetail()
print('=========================')
s3.printDetail()

Student name and department need to be set
=========================
Department for Carol needs to be set
=========================
Jon is from EEE department
=========================
###########################
Name: Bob
Department: CSE
Bob enrolled in 3 course(s):
CSE110,MAT110,ENG091
=========================
Name: Carol
Department: BBA
Carol enrolled in 1 course(s):
BUS101
=========================
Name: Jon
Department: EEE
Jon enrolled in 2 course(s):
MAT110,PHY111

#Task 21
Design a Student class so that the following output is produced upon executing the
following code:
[Hint: Each course has 3.0 credit hours. You must take at least 9.0 and at most 12.0
credit hours]

Driver Code Output

# Write your code here
# Do not change the following lines of code.

s1 = Student(“Alice”,“20103012”,“CSE”)

s2 = Student(“Bob”, “18301254”,“EEE”)

s3 = Student(“Carol”, “17101238”,“CSE”)

print(“##########################”)

print(s1.details())

print(“##########################”)

print(s2.details())

print(“##########################”)

s1.advise(“CSE110”, “MAT110”, “PHY111”)

print(“##########################”)

s2.advise(“BUS101”, “MAT120”)

print(“##########################”)

s3.advise(“MAT110”, “PHY111”, “ENG102”,

“CSE111”, “CSE230”)

##########################

Name: Alice

ID: 20103012

Department: CSE

##########################

Name: Bob

ID: 18301254

Department: EEE

##########################

Alice, you have taken 9.0 credits.

List of courses: CSE110, MAT110, PHY111

Status: Ok

##########################

Bob, you have taken 6.0 credits.

List of courses: BUS101, MAT120

Status: You have to take at least 1 more course.

##########################

Carol, you have taken 15.0 credits.

List of courses: MAT110, PHY111, ENG102,

CSE111, CSE230

Status: You have to drop at least 1 course.

In [ ]:
class Student:
  def __init__(self,name,id,dept):
    self.name=name
    self.id=id
    self.dept=dept
  def details(self):
    print('Name:',self.name)
    print('ID:',self.id)
    print('Department:',self.dept)
  def advise(self,*course):
    self.course=course
    total_course=len(self.course)
    print(f'{self.name},you have taken {total_course*3} credits')
    print('List of courses:',end='')
    for i in self.course:
      if self.course.index(i)!=len(self.course)-1:
        print(i,end=',')
      else:
        print(i)
    if total_course==2:
      print(f'Status:You have to take at least 1 more course.')
    elif total_course==3 or total_course==4:
      print(f'Status: Ok')
    elif total_course>4:
      print(f'Status:You have to drop at least {total_course-4} course.')

  


s1 = Student("Alice","20103012","CSE")
s2 = Student("Bob", "18301254","EEE")
s3 = Student("Carol", "17101238","CSE")
print("##########################")
print(s1.details())
print("##########################")
print(s2.details())
print("##########################")
s1.advise("CSE110", "MAT110", "PHY111")
print("##########################")
s2.advise("BUS101", "MAT120")
print("##########################")
s3.advise("MAT110", "PHY111", "ENG102",
"CSE111", "CSE230")

##########################
Name: Alice
ID: 20103012
Department: CSE
None
##########################
Name: Bob
ID: 18301254
Department: EEE
None
##########################
Alice,you have taken 9 credits
List of courses:CSE110,MAT110,PHY111
Status: Ok
##########################
Bob,you have taken 6 credits
List of courses:BUS101,MAT120
Status:You have to take at least 1 more course.
##########################
Carol,you have taken 15 credits
List of courses:MAT110,PHY111,ENG102,CSE111,CSE230
Status:You have to drop at least 1 course.

#Task 22
Write the Hotel class with the required methods to give the following output as shown.

Driver Code Output

# Write your code here
# Do not change the following lines of code.

h = Hotel("Lakeshore")

h.addStuff( "Adam", 26)

print("=================================")

print(h.getStuffById(1))

print("=================================")

h.addGuest(“Carol”,35,”123”)

print("=================================")

print(h.getGuestById(1))

print("=================================")

h.addGuest("Diana", 32, “431”)

print("=================================")

print(h.getGuestById(2))

print("=================================")

h.allStaffs()

print("=================================")

h.allGuest()

Staff With ID 1 is added

=================================

Staff ID: 1

Name: Adam

Age: 26

Phone no.: 000

=================================

Guest With ID 1 is created

=================================

Guest ID: 1

Name: Carol

Age: 35

Phone no.: 123

=================================

Guest With ID 2 is created

=================================

Guest ID: 2

Name: Dianal

Age: 32

Phone no.: 431

=================================

All Staffs:

Number of Staff: 1

Staff ID: 1 Name: Adam Age: 26 Phone no: 000

=================================

All Guest:

Number of Guest: 2

Guest ID: 1 Name: Carol Age: 35 Phone no.: 123

Guest ID: 2 Name: Dianal Age: 32 Phone no.: 431

In [43]:
class Hotel:
  def __init__(self,Hname):
    self.Hname=Hname
    self.count_stuff=0
    self.count_guest=0
    self.Sname=[]
    self.Sage=[]
    self.Snum=[]
    self.Gname=[]
    self.Gage=[]
    self.Gnum=[]
    self.Sid=[]
    self.Gid=[]

  def addStuff(self,name,age,num='000'):
    self.Sname.append(name)
    self.Sage.append(age)
    self.Snum.append(num)
    self.count_stuff+=1
    self.Sid.append(self.count_stuff)
    print('Staff With ID',self.count_stuff,'is added')

  def addGuest(self,name,age,num=000):
    self.Gname.append(name)
    self.Gage.append(age)
    self.Gnum.append(num)
    self.count_guest+=1
    self.Gid.append(self.count_guest)
    print('Guest With ID',self.count_guest,'is added')

  def getStuffById(self,id):
    index=self.Sid.index(id)
    return f"Stuff Id: {id}\nName:{self.Sname[index]}\nAge: {self.Sage[index]}\nPhone no.:{self.Snum[index]} "
  def getGuestById(self,id):
    index=self.Gid.index(id)
    return f"Guest Id: {id}\nName:{self.Gname[index]}\nAge: {self.Gage[index]}\nPhone no.:{self.Gnum[index]} "


  def allStaffs(self):
    print('All Staffs:')
    print('Number of Staff:',self.count_stuff)
    for i in range(len(self.Sname)):
      print(f"Staff ID: {i+1} Name: {self.Sname[i]} Age: {self.Sage[i]} Phone no.: {self.Snum[i]}")
  def allGuest(self):
    print('All Guest:')
    print('Number of Guest:',self.count_guest)
    for i in range(len(self.Gname)):
      print(f"Guest ID: {i+1} Name: {self.Gname[i]} Age: {self.Gage[i]} Phone no.: {self.Gnum[i]}")


h = Hotel("Lakeshore")
h.addStuff( "Adam", 26)
print("=================================")
print(h.getStuffById(1))
print("=================================")
h.addGuest('Carol',35,'123')
print("=================================")
print(h.getGuestById(1))
print("=================================")
h.addGuest("Diana", 32, '431')
print("=================================")
print(h.getGuestById(2))
print("=================================")
h.allStaffs()
print("=================================")
h.allGuest()

Staff With ID 1 is added
=================================
Stuff Id: 1
Name:Adam
Age: 26
Phone no.:000
=================================
Guest With ID 1 is added
=================================
Guest Id: 1
Name:Carol
Age: 35
Phone no.:123
=================================
Guest With ID 2 is added
=================================
Guest Id: 2
Name:Diana
Age: 32
Phone no.:431
=================================
All Staffs:
Number of Staff: 1
Staff ID: 1 Name: Adam Age: 26 Phone no.: 000
=================================
All Guest:
Number of Guest: 2
Guest ID: 1 Name: Carol Age: 35 Phone no.: 123
Guest ID: 2 Name: Diana Age: 32 Phone no.: 431

#Task 23
Write the Author class with the required methods to give the following outputs as
shown.

Driver Code Output

# Write your code here
# Do not change the following lines of code.

a1 = Author()

print("=================================")

a1.addBook(“Ice”, “Science Fiction”)

print("=================================")

a1.setName(“Anna Kavan”)

a1.addBook(“Ice”, “Science Fiction”)

a1.printDetail()

print("=================================")

a2 = Author(“Humayun Ahmed”)

a2.addBook(“Onnobhubon”, “Science Fiction”)

a2.addBook(“Megher Upor Bari”, “Horror”)

print(=================================")

a2.printDetail()

a2.addBook(“Ireena”, “Science Fiction”)

print("=================================")

a2.printDetail()

print("=================================")

=================================

A book can not be added without author name

=================================

Number of Book(s): 1

Author Name: Anna Kavan

Science Fiction: Ice

=================================

=================================

Number of Book(s): 2

Author Name: Humayun Ahmed

Science Fiction: Onnobhubon

Horror: Megher Upor Bari

=================================

Number of Book(s): 3

Author Name: Humayun Ahmed

Science Fiction: Onnobhubon, Ireena

Horror: Megher Upor Bari

=================================

In [4]:
class Author:
  def __init__(self,name=None):
      self.name=name
      self.science_fiction=[]
      self.horror=[]

  def addBook(self,bName,genre):
    if self.name==None:
      print('A book can not be added without author name')
    elif genre=='Science Fiction':
      self.science_fiction.append(bName)
    else:
      self.horror.append(bName)

  def setName(self,name):
    self.name=name
    
  def printDetail(self):
    print('Number of Book(s):',len(self.science_fiction)+len(self.horror))
    print('Author Name:',self.name)
    if len(self.science_fiction)>0:
      print('Science Fiction:',end='')
      for i in self.science_fiction:
         if self.science_fiction.index(i)!=len(self.science_fiction)-1:
            print(i,end=',')
         else:
             print(i)
    if len(self.horror)>0:
      print('Science Fiction:',end='')
      for i in self.horror:
         if self.horror.index(i)!=len(self.horror)-1:
            print(i,end=',')
         else:
             print(i)
    
a1 = Author()
print("=================================")
a1.addBook('Ice', 'Science Fiction')
print("=================================")
a1.setName('Anna Kavan')
a1.addBook('Ice', 'Science Fiction')
a1.printDetail()
print("=================================")
a2 = Author('Humayun Ahmed')
a2.addBook('Onnobhubon', 'Science Fiction')
a2.addBook('Megher Upor Bari', 'Horror')
print("=================================")
a2.printDetail()
a2.addBook('Ireena', 'Science Fiction')
print("=================================")
a2.printDetail()
print("=================================")

=================================
A book can not be added without author name
=================================
Number of Book(s): 1
Author Name: Anna Kavan
Science Fiction:Ice
=================================
=================================
Number of Book(s): 2
Author Name: Humayun Ahmed
Science Fiction:Onnobhubon
Science Fiction:Megher Upor Bari
=================================
Number of Book(s): 3
Author Name: Humayun Ahmed
Science Fiction:Onnobhubon,Ireena
Science Fiction:Megher Upor Bari
=================================

#Task 24
Implement the design of the Hospital, Doctor and Patient class so that the following
output is produced:

Driver Code Output

# Write your code here
# Do not change the following lines of code.

h = Hospital("Evercare")

d1 = Doctor("1d","Doctor", "Samar Kumar", "Neurologist")

h.addDoctor(d1)

print("=================================")

print(h.getDoctorByID("1d"))

print("=================================")

p1 = Patient("1p","Patient", "Kashem Ahmed", 35, 12345)

h.addPatient(p1)

print("=================================")

print(h.getPatientByID("1p"))

print("=================================")

p2 = Patient ("2p","Patient", "Tanina Haque", 26, 33456)

h.addPatient(p2)

print("=================================")

print(h.getPatientByID("2p"))

print("=================================")

h.allDoctors()

h.allPatients()

=================================

Doctor's ID: 1d

Name: Samar Kumar

Speciality: Neurologist

=================================

=================================

Patient's ID: 1p

Name: Kashem Ahmed

Age: 35

Phone no.: 12345

=================================

=================================

Patient's ID: 2p

Name: Tanina Haque

Age: 26

Phone no.: 33456

=================================

All Doctors:

Number of Doctors: 1

{'1d': ['Samar Kumar', 'Neurologist']}

All Patients:

Number of Patients: 2

{'1p': ['Kashem Ahmed', 35, 12345], '2p':

['Tanina

Haque', 26, 33456]}

In [28]:
class Hospital:
  def __init__(self,H_name):
    self.H_name=H_name
    self.list1=[]
    self.list2=[]
    self.list3=[]
    self.list4=[]
    self.list5=[]
    self.list6=[]
    self.list7=[]

  def addDoctor(self,d_obj):
    docInfo=d_obj
    self.docInfo=docInfo
    self.list1.append(self.docInfo.docID)
    self.list2.append(self.docInfo.docName)
    self.list3.append(self.docInfo.docSpecialist)

  def getDoctorByID(self,id):
    index=self.list1.index(id)
    return f"Doctor's Id: {self.list1[index]}\nName: {self.list2[index]}\nSpeciality: {self.list3[index]}"
  
  def addPatient(self,p_obj):
    patInfo=p_obj
    self.patInfo=patInfo
    self.list4.append(self.patInfo.patID)
    self.list5.append(self.patInfo.patName)
    self.list6.append(self.patInfo.patAge)
    self.list7.append(self.patInfo.patNumber)

  def getPatientByID(self,id):
       index=self.list4.index(id)
       return f"Patient's Id: {id}\nName: {self.list5[index]}\nAge: {self.list6[index]}\nPhone no.:{self.list7[index]}"

  def allDoctors(self):
      dict_1={}
      for i in range(len(self.list1)):
        dict_1[self.list1[i]]=[self.list2[i]]+[self.list3[i]]
      print(f'All Doctors:\nNumber of Doctors:{len(self.list1)}\n{dict_1}')

  def allPatients(self):
      dict_2={}
      for i in range(len(self.list4)):
        dict_2[self.list4[i]]=[self.list5[i]]+[self.list6[i]]+[self.list7[i]]
      print(f'All patients:\nNumber of patients:{len(self.list4)}\n{dict_2}')


class Doctor:
  def __init__(self,d_id,d_profession,d_name,d_specialist):
        self.docID=d_id
        self.doc_prof=d_profession
        self.docName=d_name
        self.docSpecialist=d_specialist

class Patient:
  def __init__(self,p_id,p_profession,p_name,p_age,p_number):
        self.patID=p_id
        self.pat_prof=p_profession
        self.patName=p_name
        self.patAge=p_age
        self.patNumber=p_number
         




# Do not change the following lines of code.
h = Hospital("Evercare")
d1 = Doctor("1d","Doctor", "Samar Kumar", "Neurologist")
h.addDoctor(d1)
print("=================================")
print(h.getDoctorByID("1d"))
print("=================================")
p1 = Patient("1p","Patient", "Kashem Ahmed", 35, 12345)
h.addPatient(p1)
print("=================================")
print(h.getPatientByID("1p"))
print("=================================")
p2 = Patient ("2p","Patient", "Tanina Haque", 26, 33456)
h.addPatient(p2)
print("=================================")
print(h.getPatientByID("2p"))
print("=================================")
h.allDoctors()
h.allPatients()

=================================
Doctor's Id: 1d
Name: Samar Kumar
Speciality: Neurologist
=================================
=================================
Patient's Id: 1p
Name: Kashem Ahmed
Age: 35
Phone no.:12345
=================================
=================================
Patient's Id: 2p
Name: Tanina Haque
Age: 26
Phone no.:33456
=================================
All Doctors:
Number of Doctors:1
{'1d': ['Samar Kumar', 'Neurologist']}
All patients:
Number of patients:2
{'1p': ['Kashem Ahmed', 35, 12345], '2p': ['Tanina Haque', 26, 33456]}

# Task 25

Design the Vaccine and Person class so that the following expected output is
generated.
[N.B: Students will get vaccines on a priority basis. So, age for students doesn’t matter]

Driver Code Output

# Write your code here

astra = Vaccine("AstraZeneca", "UK", 60)

modr = Vaccine("Moderna", "UK", 30)

sin = Vaccine("Sinopharm", "China", 30)

p1 = Person("Bob", 21, "Student")

print("=================================")

p1.pushVaccine(astra)

print("=================================")

p1.showDetail()

print("=================================")

p1.pushVaccine(sin, "2nd Dose")

print("=================================")

p1.pushVaccine(astra, "2nd Dose")

print("=================================")

p1.showDetail()

print("=================================")

p2 = Person("Carol", 23, "Actor")

print("=================================")

p2.pushVaccine(sin)

print("=================================")

p3 = Person("David", 34)

print("=================================")


p3.pushVaccine(modr)

print("=================================")

p3.showDetail()

print("=================================")

p3.pushVaccine(modr, "2nd Dose")

=================================

1st dose done for Bob

=================================

Name: Bob Age: 21 Type: Student

Vaccine name: AstraZeneca

1st dose: Given

2nd dose: Please come after 60 days

=================================

Sorry Bob, you can’t take 2 different vaccines

=================================

2nd dose done for Bob

=================================

Name: Bob Age: 21 Type: Student

Vaccine name: AstraZeneca

1st dose: Given

2nd dose: Given

=================================

=================================

Sorry Carol, Minimum age for taking vaccines is

25 years now.

=================================

=================================

1st dose done for David

=================================

Name: David Age: 34 Type: General Citizen

Vaccine name: Moderna

1st dose: Given

2nd dose: Please come after 30 days

=================================

2nd dose done for David