# Task 1

Write a Student class to get the desired output as shown below.
1. Create a Student class and a class variable called ID initialized with 0.
2. Create a constructor that takes 4 parameters: name, department, age and cgpa.
3. Write a get_details() method to represent all the details of a Student
4. Write a class method from_String() that takes 1 parameter which includes
name, department, age and cgpa all four attributes in string.
5. Explain the difference between a class variable and an instance variable. Print
your answer at the very end of your code.
6. What is the difference between an instance method and class method? Print your
answer at the very end
#Write your code here for subtasks 1-6.
s1 = Student("Samin", "CSE", 21, 3.91)

s1.get_details()

print("-----------------------")

s2 = Student("Fahim", "ECE", 21, 3.85)

s2.get_details()

print("-----------------------")

s3 = Student("Tahura", "EEE", 22, 3.01)

s3.get_details()

print("-----------------------")

s4 = Student.from_String("Sumaiya-BBA-23-3.96")

s4.get_details()

.Write the answer of subtask 5 here

.Write the answer of subtask 6 here

.You are not allowed to change the code above

OUTPUT

ID: 1

Name: Samin

Department: CSE

Age: 21

CGPA: 3.91

-----------------------

ID: 2

Name: Fahim

Department: ECE

Age: 21

CGPA: 3.85

-----------------------

ID: 3

Name: Tahura

Department: EEE

Age: 22

CGPA: 3.01

-----------------------

ID: 4

Name: Sumaiya

Department: BBA

Age: 23

CGPA: 3.96

In [ ]:
class Student:
  ID=0
  def __init__(self,name,department,age,cgpa):
    self.name=name
    self.department=department
    self.age=age
    self.cgpa=cgpa
    Student.ID+=1
    self.id=Student.ID 

  def get_details(self):
    print(f'ID:{self.id}\nName:{self.name}\nDepartment:{self.department}\nAge:{self.age}\nCGPA:{self.cgpa}')
  
  @classmethod
  def from_String(self,info):
    list1=info.split('-')
    new_student=Student(list1[0],list1[1],int(list1[2]),float(list1[3]))
    return new_student

s1 = Student("Samin", "CSE", 21, 3.91)
s1.get_details()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.get_details()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.get_details()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.get_details()
print('we write class variable before constructor and can be used by all instance and subclasses where instance variables are stored inside constructor and only belong to one specific class.')
print('Instance methods can access class variables and class methods directly. Class methods can access class variables and class methods directly. Class methods cannot access instance variables or instance methods directly—they must use an object reference.')

ID:1
Name:Samin
Department:CSE
Age:21
CGPA:3.91
-----------------------
ID:2
Name:Fahim
Department:ECE
Age:21
CGPA:3.85
-----------------------
ID:3
Name:Tahura
Department:EEE
Age:22
CGPA:3.01
-----------------------
ID:4
Name:Sumaiya
Department:BBA
Age:23
CGPA:3.96
we write class variable before constructor and can be used by all instance and subclasses where instance variables are stored inside constructor and only belong to one specific class.
Instance methods can access class variables and class methods directly. Class methods can access class variables and class methods directly. Class methods cannot access instance variables or instance methods directly—they must use an object reference.

# Task 2

Write the Assassin class so that the given code provides the expected output.
1. Create Assassin class
2. Create 1 class variable
3. Create 1 class method titled ‘failureRate()’
4. Create 1 class method titled ‘failurePercentage()’
5. Maximum success_rate is 100
[You are not allowed to change the code below]
#Write your code here

john_wick = Assassin('John Wick', 100)

john_wick.printDetails()

print('================================')

nagisa = Assassin.failureRate("Nagisa", 20)

nagisa.printDetails()

print('================================')

akabane = Assassin.failurePercentage("Akabane", "10%")

akabane.printDetails()

Output:

Name: John Wick

Success rate: 100%

Total number of Assassin: 1

============================

Name: Nagisa

Success rate: 80%

Total number of Assassin: 2

============================

Name: Akabane

Success rate: 90%

Total number of Assassin: 3

In [ ]:
class Assassin:
  number=0
  def __init__(self,name,s_rate):
    self.name=name
    self.s_rate=s_rate
    Assassin.number+=1
    self.num=Assassin.number
  def printDetails(self):
    print(f'Name:{self.name}\nSuccess rate:{self.s_rate}%\nTotal number of Assassin:{self.num}')

  @classmethod
  def failureRate(cls,name,f_rate):   #when we declare a class method we will write cls instead of self 
    s_rate=100-f_rate
    obj=cls(name,s_rate)              #when we declare a class method we will write cls instead of the class name itself(naming convention)
    return obj 

  @classmethod
  def failurePercentage(cls,name,f_per):
    s_rate=100-int(f_per[0:len(f_per)-1])
    obj=cls(name,s_rate)
    return obj

john_wick = Assassin('John Wick', 100)
john_wick.printDetails()
print('================================')
nagisa = Assassin.failureRate("Nagisa", 20)
nagisa.printDetails()
print('================================')
akabane = Assassin.failurePercentage("Akabane", "10%")
akabane.printDetails()

Name:John Wick
Success rate:100%
Total number of Assassin:1
================================
Name:Nagisa
Success rate:80%
Total number of Assassin:2
================================
Name:Akabane
Success rate:90%
Total number of Assassin:3

# Task 3

Implement the design of the Passenger class so that the following output is produced:

The assumption is Bus base-fare is 450 taka. A passenger can carry upto 20 kg for free.
50 taka will be added if bag weight is between 21 and 50 kg. 100 taka will be added if
bag weight is greater than 50 kg.
[You are not allowed to change the code below]
# Write your code here

print(“Total Passenger:”, Passenger.count)

p1 = Passenger(“Jack”)

p1.set_bag_weight(90)

p2 = Passenger(“Carol”)

p2.set_bag_weight(10)

p3 = Passenger(“Mike”)

p3.set_bag_weight(25)

print("=========================")

p1.printDetail()

print("=========================")

p2.printDetail()

print("=========================")

p3.printDetail()

print("=========================")

print(“Total Passenger:”, Passenger.count)

Output:

Total Passenger: 0

=========================

Name: Jack

Bus Fare: 550 taka

=========================

Name: Carol

Bus Fare: 450 taka

=========================

Name: Mike

Bus Fare: 500 taka

=========================

Total Passenger: 3

In [ ]:
class Passenger:
  count=0
  def __init__(self,name):
    self.name=name
    self.weight=0
    Passenger.count+=1
  def set_bag_weight(self,weight):
    self.weight=weight
  def printDetail(self):
     print('Name:',self.name)
     if self.weight<=20:
       print('Bus Fare: 450 taka')
     elif self.weight<=50:
       print('Bus Fare: 500 taka')
     else:
       print('Bus Fare: 550 taka')

print('Total Passenger:', Passenger.count)
p1 = Passenger('Jack')
p1.set_bag_weight(90)
p2 = Passenger('Carol')
p2.set_bag_weight(10)
p3 = Passenger('Mike')
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print('Total Passenger:', Passenger.count)

Total Passenger: 0
=========================
Name: Jack
Bus Fare: 550 taka
=========================
Name: Carol
Bus Fare: 450 taka
=========================
Name: Mike
Bus Fare: 500 taka
=========================
Total Passenger: 3

# Task 4

Implement the design of the Travel class so that the following output is produced:

[You are not allowed to change the code below]
# Write your code here

print(“No. of Traveller =”, Travel.count)

print("=======================")

t1 = Travel("Dhaka","India")

print(t1.display_travel_info())

print("=======================")

t2 = Travel("Kuala Lampur","Dhaka")

t2.set_time(23)

print(t2.display_travel_info())

print("=======================")

t3 = Travel("Dhaka","New_Zealand")

t3.set_time(15)

t3.set_destination("Germany")

print(t3.display_travel_info())

print("=======================")

t4 = Travel("Dhaka","India")

t4.set_time(9)

t4.set_source("Malaysia")

t4.set_destination("Canada")

print(t4.display_travel_info())

print("=======================")

print(“No. of Traveller =”, Travel.count)

Output

No. of Traveller = 0

=======================

Source: Dhaka

Destination:India

Flight Time:1:00

=======================

Source: Kuala Lampur

Destination:Dhaka

Flight Time:23:00

=======================

Source: Dhaka

Destination:Germany

Flight Time:15:00

=======================

Source: Malaysia

Destination:Canada

Flight Time:9:00

=======================

No of Traveller = 4

In [ ]:
class Travel:
  count=0
  def __init__(self,source,dest):
    self.source=source
    self.dest=dest
    Travel.count+=1
    self.time=1

  def display_travel_info(self):
    return f'Source:{self.source}\nDestintion:{self.dest}\nFlight Time:{self.time}:00'

  def set_time(self,time):
    self.time=time
  def set_destination(self,dest):
    self.dest=dest
  def set_source(self,source):
    self.source=source 
    
print('No. of Traveller =', Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print('No. of Traveller =', Travel.count)

No. of Traveller = 0
=======================
Source:Dhaka
Destintion:India
Flight Time:1:00
=======================
Source:Kuala Lampur
Destintion:Dhaka
Flight Time:23:00
=======================
Source:Dhaka
Destintion:Germany
Flight Time:15:00
=======================
Source:Malaysia
Destintion:Canada
Flight Time:9:00
=======================
No. of Traveller = 4

# Task 5

Create an Employee Class that will have

● Two instance variable: name and workingPeriod

● A class method named employeeByJoiningYear():

o To create an Employee object by joining year for calculating the working
period

o It will have two Parameter name and year

● A static method experienceCheck() to check if an Employee is experienced or not

o It will take working period and gender as parameter

o If an employee’s working period is less than 3, he or she is not experienced

[You are not allowed to change the code below]
# Write your code here

employee1 = Employee('Dororo', 3)

employee2 = Employee.employeeByJoiningYear('Harry', 2016)

print(employee1.workingPeriod)

print(employee2.workingPeriod)

print(employee1.name)

print(employee2.name)

print(Employee.experienceCheck(2, "male"))

print(Employee.experienceCheck(3, "female"))

Output

3

6

Dororo

Harry

He is not experienced

She is experienced

In [ ]:
class Employee:
  def __init__(self,name,w_period):
     self.name=name
     self.workingPeriod=w_period
  @classmethod 
  def employeeByJoiningYear(cls,name,year):
    workingPeriod=(2022-year)
    return Employee(name,workingPeriod)
  @staticmethod
  def experienceCheck(year,gen):
    if year>=3:
      if gen=='male':
        return 'He is experienced'
      else:
        return 'She is experienced'
    else:
      if gen=='male':
        return 'He is not experienced'
      else:
        return 'she is not experienced'


employee1 = Employee('Dororo', 3)
employee2 = Employee.employeeByJoiningYear('Harry', 2016)
print(employee1.workingPeriod)
print(employee2.workingPeriod)
print(employee1.name)
print(employee2.name)
print(Employee.experienceCheck(2, "male"))
print(Employee.experienceCheck(3, "female"))

3
6
Dororo
Harry
He is not experienced
She is experienced

# Task 6

Implement the design of the Laptop class so that the following output is produced
[You are not allowed to change the code below]
# Write your code here

lenovo = Laptop("Lenovo", 5);

dell = Laptop("Dell", 7);

print(lenovo.name, lenovo.count)

print(dell.name, dell.count)

print("Total number of Laptops", Laptop.laptopCount)

Laptop.advantage()

Laptop.resetCount()

print("Total number of Laptops", Laptop.laptopCount)

Output

Lenovo 5

Dell 7

Total number of Laptops 12

Laptops are portable

Total number of Laptops 0

In [ ]:
class Laptop:
  laptopCount=0
  def __init__(self,name,ammount):
    self.name=name
    self.count=ammount
    Laptop.laptopCount+=ammount
  @staticmethod
  def advantage():
    print('Laptops are portable')
  @staticmethod
  def resetCount():
    Laptop.laptopCount=0
  

lenovo = Laptop("Lenovo", 5);
dell = Laptop("Dell", 7);
print(lenovo.name, lenovo.count)
print(dell.name, dell.count)
print("Total number of Laptops", Laptop.laptopCount)
Laptop.advantage()
Laptop.resetCount()
print("Total number of Laptops", Laptop.laptopCount)

Lenovo 5
Dell 7
Total number of Laptops 12
Laptops are portable
Total number of Laptops 0

# Task 7

Design Cat class for the following code to get the output as shown.

You have already solved this problem in assignment 4 using constructor overloading.

Now, solve this again but this time DO NOT USE CONSTRUCTOR OVERLOADING.
Hint: You will have to use classmethods.

[You are not allowed to change the code below]
# Write your code here

print("Total number of cats:", Cat.Number_of_cats)

c1 = Cat.no_parameter()

c2 = Cat.first_parameter("Black")

c3 = Cat("Brown", "jumping")

c4 = Cat("Red", "purring")

c5 = Cat.second_parameter("playing")

print("=======================")

c1.printCat()

c2.printCat()

c3.printCat()

c4.printCat()

c5.printCat()

c1.changeColor("Blue")

c3.changeColor("Purple")

c1.printCat()

c3.printCat()

print("=======================")

print("Total number of cats:", Cat.Number_of_cats)

Output:

Total number of cats: 0

=======================

White cat is sitting

Black cat is sitting

Brown cat is jumping

Red cat is purring

Grey cat is playing

Blue cat is sitting

Purple cat is jumping

=======================

Total number of cats: 5

In [ ]:
class Cat:
  Number_of_cats=0
  def __init__(self,clr,action):
    self.clr=clr
    self.action=action
    Cat.Number_of_cats+=1
  def printCat(self):
    print(f'{self.clr} cat is {self.action}')

  @classmethod
  def no_parameter(cls):
    return Cat('White','sitting')
  @classmethod
  def first_parameter(cls,clr):
    return Cat(clr,'sitting')
  @classmethod
  def second_parameter(cls,action):
    return Cat('Grey',action)
  
  def changeColor(self,clr):
    self.clr=clr 

print("Total number of cats:", Cat.Number_of_cats)
c1 = Cat.no_parameter()
c2 = Cat.first_parameter("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c5 = Cat.second_parameter("playing")
print("=======================")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c5.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()
print("=======================")
print("Total number of cats:", Cat.Number_of_cats)

Total number of cats: 0
=======================
White cat is sitting
Black cat is sitting
Brown cat is jumping
Red cat is purring
Grey cat is playing
Blue cat is sitting
Purple cat is jumping
=======================
Total number of cats: 5

# Task 8

Write a Cylinder class to get the desired output as shown below.
1. You will have to create a Cylinder class.
2. You will have to create 2 class variables.
3. Create a required constructor.
4. Write 2 class methods:
• One that takes the height first and then the radius and then swaps
• One that takes a string where the radius and height values are separated
with a hyphen.
Write 2 static methods:

• One that calculates the area of a whole cylinder (formula: 2πr
2 + 2πrh)

• Another that calculates the volume of a cylinder (formula: πr
2h)

**Observe the output values carefully to understand how the radius and height values
are changing.
[You are not allowed to change the code below]
# Write your code here

c1 = Cylinder(0,0)

Cylinder.area(c1.radius,c1.height)

Cylinder.volume(c1.radius,c1.height)

print("===============================")

c2 = Cylinder.swap(8,3)

c2.area(c2.radius,c2.height)

c2.volume(c2.radius,c2.height)

print("===============================")

c3 = Cylinder.changeFormat("7-13")

c3.area(c3.radius,c3.height)

c3.volume(c3.radius,c3.height)

print("===============================")

Cylinder(0.3,5.56).area(Cylinder.radius,Cylinder.height)

print("===============================")

Cylinder(3,5).volume(Cylinder.radius,Cylinder.height))

Output:

Default radius=5 and height=18.

Updated: radius=0 and height=0.

Area: 0.0

Volume: 0.0

===============================

Default radius=0 and height=0.

Updated: radius=3 and height=8.

Area: 207.34511513692635

Volume: 226.1946710584651

===============================

Default radius=3 and height=8.

Updated: radius=7.0 and height=13.0.

Area: 879.645943005142

Volume: 2001.1945203366981

===============================

Default radius=7.0 and height=13.0.

Updated: radius=0.3 and height=5.56.

Area: 11.045839770021713

===============================

Default radius=0.3 and height=5.56.

Updated: radius=3 and height=5.

Volume: 141.3716694115407

In [ ]:
import math
class Cylinder:
  radius=5
  height=18
  def __init__(self,r,h):
    print(f'Default radius={Cylinder.radius} and height={Cylinder.height}.')
    self.radius=r
    self.height=h
    Cylinder.radius=r
    Cylinder.height=h
    print(f'Updated radius={Cylinder.radius} and height={Cylinder.height}.') 
  @classmethod
  def swap(cls,h,r):
    return Cylinder(r,h)
  @classmethod
  def changeFormat(cls,info):
    list1=info.split('-')
    r=float(list1[0])
    h=float(list1[1])
    return Cylinder(r,h)
  @staticmethod
  def area(r,h):
    area=(2*math.pi*r**2)+(2*math.pi*r*h)
    print('Area:',area)
  @staticmethod
  def volume(r,h):
    vol=(math.pi*r**2*h)
    print('Volume:',vol)

c1 = Cylinder(0,0)
Cylinder.area(c1.radius,c1.height)
Cylinder.volume(c1.radius,c1.height)
print("===============================")
c2 = Cylinder.swap(8,3)
c2.area(c2.radius,c2.height)
c2.volume(c2.radius,c2.height)
print("===============================")
c3 = Cylinder.changeFormat("7-13")
c3.area(c3.radius,c3.height)
c3.volume(c3.radius,c3.height)
print("===============================")
Cylinder(0.3,5.56).area(Cylinder.radius,Cylinder.height)
print("===============================")
Cylinder(3,5).volume(Cylinder.radius,Cylinder.height)

Default radius=5 and height=18.
Updated radius=0 and height=0.
Area: 0.0
Volume: 0.0
===============================
Default radius=0 and height=0.
Updated radius=3 and height=8.
Area: 207.34511513692635
Volume: 226.1946710584651
===============================
Default radius=3 and height=8.
Updated radius=7.0 and height=13.0.
Area: 879.645943005142
Volume: 2001.1945203366981
===============================
Default radius=7.0 and height=13.0.
Updated radius=0.3 and height=5.56.
Area: 11.045839770021713
===============================
Default radius=0.3 and height=5.56.
Updated radius=3 and height=5.
Volume: 141.3716694115407

# Task 9

Write the Student class so that the given code provides the expected output.
1. Create Student class
2. Create 3 class variable
3. Create 1 class method for object creation
4. Create 1 class method for printing
[You are not allowed to change the code below]

# Write your code here

Student.printDetails()

print('#########################')

mikasa = Student('Mikasa Ackerman', "CSE")

mikasa.individualDetail()

print('------------------------------------------')

Student.printDetails()

print('========================')

harry = Student.createStudent('Harry Potter', "Defence Against Dark
Arts", "Hogwarts School")

harry.individualDetail()

print('-------------------------------------------')

Student.printDetails()

print('=========================')

levi = Student.createStudent("Levi Ackerman", "CSE")

levi.individualDetail()

print('--------------------------------------------')

Student.printDetails()

Output:

Total Student(s): 0

BRAC University Student(s): 0

Other Institution Student(s): 0

################################

Name: Mikasa Ackerman

Department: CSE

Institution: BRAC University

------------------------------------------------------

Total Student(s): 1

BRAC University Student(s): 1

Other Institution Student(s): 0

===============================

Name: Harry Potter

Department: Defence Against Dark Arts

Institution: Hogwarts School

------------------------------------------------------

Total Student(s): 2

BRAC University Student(s): 1

Other Institution Student(s): 1

===============================

Name: Levi Ackerman

Department: CSE

Institution: BRAC University

------------------------------------------------------

Total Student(s): 3

BRAC University Student(s): 2

Other Institution Student(s): 1

In [ ]:
class Student:
  t_student=0
  brac_stu=0
  other_stu=0
  def __init__(self,name,dept,inst='Brac University'):
    self.name=name
    self.dept=dept
    self.inst=inst
    Student.t_student+=1
    if self.inst !='Brac University':
      Student.other_stu+=1
    else:
      Student.brac_stu+=1
  def individualDetail(self):
    print(f'Name:{self.name}\nDepartment:{self.dept}\nInstitution:{self.inst}')
  @classmethod
  def printDetails(cls):
    print(f'Total Student(s):{cls.t_student}\nBRAC University Student(s):{cls.brac_stu}\nOther Institution Student(s):{cls.other_stu}')
  @classmethod
  def createStudent(cls,name,dept,inst='Brac University'):
    return Student(name,dept,inst)


Student.printDetails()
print('#########################')
mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()
print('========================')
harry = Student.createStudent('Harry Potter', "Defence Against DarkArts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()
print('=========================')
levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

Total Student(s):0
BRAC University Student(s):0
Other Institution Student(s):0
#########################
Name:Mikasa Ackerman
Department:CSE
Institution:Brac University
------------------------------------------
Total Student(s):1
BRAC University Student(s):1
Other Institution Student(s):0
========================
Name:Harry Potter
Department:Defence Against DarkArts
Institution:Hogwarts School
-------------------------------------------
Total Student(s):2
BRAC University Student(s):1
Other Institution Student(s):1
=========================
Name:Levi Ackerman
Department:CSE
Institution:Brac University
--------------------------------------------
Total Student(s):3
BRAC University Student(s):2
Other Institution Student(s):1

# Task 10

Write the SultansDine class so that the given code provides the expected output.
[You are not allowed to change the code below]
# Write your code here

SultansDine.details()

print('########################')

dhanmodi = SultansDine('Dhanmondi')

dhanmodi.sellQuantity(25)

dhanmodi.branchInformation()

print('-----------------------------------------')

SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')

baily_road.sellQuantity(15)

baily_road.branchInformation()

print('-----------------------------------------')

SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')

gulshan.sellQuantity(9)

gulshan.branchInformation()

print('-----------------------------------------')

SultansDine.details()

Output:

Total Number of branch(s): 0

Total Sell: 0 Taka

#################################

Branch Name: Dhanmondi

Branch Sell: 10000 Taka

-----------------------------------------

Total Number of branch(s): 1

Total Sell: 10000 Taka

Branch Name: Dhanmondi, Branch Sell: 10000 Taka

Branch consists of total sell's: 100.00%

================================

Branch Name: Baily Road

Branch Sell: 5250 Taka

-----------------------------------------

Total Number of branch(s): 2

Total Sell: 15250 Taka

Branch Name: Dhanmondi, Branch Sell: 10000 Taka

Branch consists of total sell's: 65.57%

Branch Name: Baily Road, Branch Sell: 5250 Taka

Branch consists of total sell's: 34.43%

================================

Branch Name: Gulshan

Branch Sell: 2700 Taka
-----------------------------------------

Total Number of branch(s): 3

Total Sell: 17950 Taka

Branch Name: Dhanmondi, Branch Sell: 10000 Taka

Branch consists of total sell's: 55.71%

Branch Name: Baily Road, Branch Sell: 5250 Taka

Branch consists of total sell's: 29.25%

Branch Name: Gulshan, Branch Sell: 2700 Taka

Branch consists of total sell's: 15.04%

Subtaks:

1. Create SultansDine class

2. Create 2 class variable and 1 class list

3. Create 1 class method

4. Calculation of branch sell is given below

a. If sellQuantity < 10:

    i. Branch_sell = quantity * 300

b. Else if sellQuantity < 20:

    i. Branch_sell = quantity * 350

c. Else

    i. Branch_sell = quantity * 400
    
5. Calculation of branch’s sell percentage = (branch’s sell / total sell) * 100

In [ ]:
class SultansDine:
  num_branch=0
  sell=0
  branches=[]
  def __init__(self,branch):
    self.branch=branch
    SultansDine.num_branch+=1
    SultansDine.branches.append(self)
    self.quantity=0
    self.sell=SultansDine.sell

  def branchInformation(self):
    print('Branch Name:',self.branch)
    print('Branch Sell:',self.sell)

  def sellQuantity(self,quan):
    if quan<10:
      self.sell=quan*300
    elif quan<20:
      self.sell=quan*350
    else:
      self.sell=quan*400

  @classmethod
  def details(cls):
    Total_sell=0
    for i in cls.branches:
      Total_sell+=i.sell 
    print('Total Number of branch(s):',cls.num_branch)
    print('Total Sell:',Total_sell)
    for i in cls.branches:
      print(f'Branch Name: {i.branch},Branch Sell: {i.sell}')
      print(f"Branch consists of total sell's: {round((i.sell/Total_sell)*100,2)}%")

SultansDine.details()
print('########################')
dhanmodi = SultansDine('Dhanmondi')
dhanmodi.sellQuantity(25)
dhanmodi.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s): 0
Total Sell: 0
########################
Branch Name: Dhanmondi
Branch Sell: 10000
-----------------------------------------
Total Number of branch(s): 1
Total Sell: 10000
Branch Name: Dhanmondi,Branch Sell: 10000
Branch consists of total sell's: 100.0%
========================
Branch Name: Baily Road
Branch Sell: 5250
-----------------------------------------
Total Number of branch(s): 2
Total Sell: 15250
Branch Name: Dhanmondi,Branch Sell: 10000
Branch consists of total sell's: 65.57%
Branch Name: Baily Road,Branch Sell: 5250
Branch consists of total sell's: 34.43%
========================
Branch Name: Gulshan
Branch Sell: 2700
-----------------------------------------
Total Number of branch(s): 3
Total Sell: 17950
Branch Name: Dhanmondi,Branch Sell: 10000
Branch consists of total sell's: 55.71%
Branch Name: Baily Road,Branch Sell: 5250
Branch consists of total sell's: 29.25%
Branch Name: Gulshan,Branch Sell: 2700
Branch consists of total sell's: 15.04%

#extra
input:

Giraffe = Toy(“Giraffe”, “soft”)

Giraffe.addCall()

Giraffe.addFeatureDetail(“height”, 10)

Giraffe.addFeatureDetail(“age”, 10)

Giraffe.addFeature(“age”)

Giraffe.addFeatureDetail(“age”, 10)

Elephant = Toy(“Elephant”, “acd”)

Elephant.showName()

Giraffe.setName(“babyGiraffe”)

age_of_giraffe =Giraffe.getAge()

type_of_giraffe = Giraffe.getType()

print(Giraffe.getName(), “ is a”, age_of_giraffe,”

year old”, type_of_giraffe, “ type toy”)

print(Toy.count)

Toy.removeToy(“babyGiraffe”)

print(Toy.count)

output:

A new soft toy named “Giraffe” has been created!

Giraffe did not get any calls :(

New feature detail added for Giraffe:

height = 10

Error! Cannot add detail that does not exist. Please
use addFeature method first

New feature detail added for Giraffe:

age = 10

Error! Toys can only be of “soft” or “plush” type

Toy does not have a name.

babyGiraffe is a 10 year old soft type toy

2

1

In [25]:

class Toy:
  count=0
  feature_list=['height','color','weight']
  animal_list=[]
  def __init__(self,name,toyType):
    Toy.count+=1
    if toyType == 'soft' or toyType=='plush':
     Toy.animal_list.append(name)
     self.name=name
     self.toyType=toyType
     print(f"A new {toyType} toy named '{name}' has been created!")
    else:
      print('Error! Toys can only be of “soft” or “plush” type')
      self.name=None

  def addCall(self):
    print(f'{self.name} did not get any calls :(')

  def addFeatureDetail(self,feature,val):
    if feature not in Toy.feature_list:
        print('Error! Cannot add detail that does not exist. Please use add Feature method first')
    else:
        self.age=val
        print(f'New feature detail added for {self.name}:')
        print(f'{feature} = {val}')

  def addFeature(self,feature):
        Toy.feature_list.append(feature)

  def showName(self):
      if self.name != None:
        print(self.name)
      else:
        print('Toy does not have a name.')

  def getName(self):
    return self.name

  def setName(self,name):
    Toy.animal_list.remove(self.name)
    self.name=name
    Toy.animal_list.append(name)

  def getAge(self):
    return self.age

  def getType(self):
    return self.toyType
  
  @classmethod
  def removeToy(cls,name):
    cls.animal_list.remove(name)
    cls.count-=1

Giraffe = Toy('Giraffe', 'soft')
Giraffe.addCall()
Giraffe.addFeatureDetail('height', 10)
Giraffe.addFeatureDetail('age', 10)
Giraffe.addFeature('age')
Giraffe.addFeatureDetail('age', 10)
Elephant = Toy('Elephant', 'acd')
Elephant.showName()
Giraffe.setName('babyGiraffe')
age_of_giraffe =Giraffe.getAge()
type_of_giraffe = Giraffe.getType()
print(Giraffe.getName(), 'is a', age_of_giraffe,'year old', type_of_giraffe, 'type toy')
print(Toy.count)
Toy.removeToy('babyGiraffe')
print(Toy.count)

A new soft toy named 'Giraffe' has been created!
Giraffe did not get any calls :(
New feature detail added for Giraffe:
height = 10
Error! Cannot add detail that does not exist. Please use add Feature method first
New feature detail added for Giraffe:
age = 10
Error! Toys can only be of “soft” or “plush” type
Toy does not have a name.
babyGiraffe is a 10 year old soft type toy
2
1

In [27]:
class ClassA:
 def __init__(self, x, sum, value):
   self.x = x
   self.sum = sum
   if value % 3 == 0:
     self.y = 7
   else:
     self.__y =9
 def methodA(self, x):
   try:
     self.y = x + self.sum + self.x
     self.sum = x + self.y
     z = ClassA(1, 4, 8)
     z.sum = self.sum + self.__y
     self.methodB(z)
     print(self.x, self.y, self.sum)
   except:
     print(1, 1, 1)
 def methodB(self, a):
   try:
     y = 3
     a.x = self.x + self.sum
     self.sum = a.x + a.y + y
     print(a.x, a.y, a.sum)
   except:
     print(0 , 0 , 0)

a= ClassA(1, 2, 3)
a.methodA(5)
b= ClassA(2, 4, 7)
b.methodA(5)

1 1 1
0 0 0
2 11 16