In [ ]:
# task 2
class myList:
  def __init__(self,*n):
    self.list1=list(n)
    self.total=0
    self.ave=0
  

  def sum(self):
    self.total=sum(self.list1)
    print("sum:",self.total)
  
  def merge(self,*n):
    self.list1+=list(n)
  
  def average(self):
    if len(self.list1)==0:
      print("Average:",self.ave)
    
    else:
      self.ave= (self.total/len(self.list1))
      print("Average:",self.ave)

  
l1 =  myList(2,3,4,5,6) #you might need a list inside your class to store the values
l1.sum()
l1.merge(4,5,9)
l1.sum()
l1.average()
print("-----------------------------")
l2 =  myList()
l2.average()
l2.merge(1,2,4,8)
l2.sum()

sum: 20
sum: 38
Average: 4.75
-----------------------------
Average: 0
sum: 15

In [ ]:
#task3 
class Bird:
  def __init__(self,name,y=False):
    self.name=name
    self.y=y
    self.type1="Flightless Birds"
    

  def fly(self):
    if self.y==True:
      print(f"{self.name} can fly")
    else:
      print(f"{self.name} can not fly")
    
  def setType(self,t1):
    self.type1=t1

  def printDetail(self):
    print("Name:",self.name)
    print("Type:",self.type1)
    

ostrich = Bird('Ostrich')
duck = Bird("Duck", True)
owl = Bird('Owl', True)
print("###########################")
ostrich.fly()
duck.fly()
owl.fly()
duck.setType('Water Birds')
owl.setType('Birds of Prey')
print("=========================")
ostrich.printDetail()
print("=========================")
duck.printDetail()
print("=========================")
owl.printDetail()

###########################
Ostrich can not fly
Duck can fly
Owl can fly
=========================
Name: Ostrich
Type: Flightless Birds
=========================
Name: Duck
Type: Water Birds
=========================
Name: Owl
Type: Birds of Prey

In [ ]:
#task 4 
class Account:
  count=0
  def __init__(self,name,age,occupation,amount):
    self.name=name
    self.age=age
    self.occupation=occupation
    self.amount=amount
    Account.count+=1
  
  def addMoney(self,x):
    self.amount+=x

  def printDetails(self):
    print("Name: ",self.name)
    print("Age: ",self.age)
    print("Occupation: ",self.occupation)
    print("Total Amount: ",self.amount)

  def withdrawMoney(self,x):
    self.amount-=x

print('No of account holders:', Account.count)
print("=========================")
p1 = Account("Abdul", 45, "Service Holder", 500000)
p1.addMoney(300000)
p1.printDetails()
print("=========================")
p2 = Account("Rahim", 55, "Businessman", 700000)
p2.withdrawMoney(700000)
p2.printDetails()
print("=========================")
p3 = Account("Ashraf", 62, "Govt. Officer", 200000)
p3.withdrawMoney(250000)
p3.printDetails()
print("=========================") 
print('No of account holders:', Account.count)

No of account holders: 0
=========================
Name:  Abdul
Age:  45
Occupation:  Service Holder
Total Amount:  800000
=========================
Name:  Rahim
Age:  55
Occupation:  Businessman
Total Amount:  0
=========================
Name:  Ashraf
Age:  62
Occupation:  Govt. Officer
Total Amount:  -50000
=========================
No of account holders: 3

In [ ]:
#task 5

class Smartphone:
  def __init__(self,phone_name=None):
    self.phone_name=phone_name
    self.feature={}
    
    

  def addFeature(self,category,name):
    if self.phone_name!=None:
      if category not in self.feature.keys():
        self.feature[category]=[name]
      else:
        self.feature[category].append(name)
    else:
      print("Feature can not be added without phone name")

  def setName(self,name):
    self.phone_name=name

  def printDetail(self):
    print("Phone Name:",self.phone_name)
    
    for key,value in self.feature.items():
      a=''
      for i in range(len(value)):
        if i!=len(value)-1:
          a+=value[i]
          a+=","
        else:
          a+=value[i]
      
      print(f"{key}:{a}")

s1 = Smartphone()
print("=================================")
s1.addFeature('Display', '6.1 inch')
print("=================================")
s1.setName('Samsung Note 20')
s1.addFeature('Display', '6.1 inch')
s1.printDetail()
print('=================================')
s2 = Smartphone('Iphone 12 Pro')
s2.addFeature('Display', '6.2 inch')
s2.addFeature('“Ram”', '6 Gb”')
print('=================================')
s2.printDetail()
s2.addFeature('Display', 'Amoled panel')
s2.addFeature('Ram', 'DDR5')
print("=================================")
s2.printDetail()
print("=================================")

=================================
Feature can not be added without phone name
=================================
Phone Name: Samsung Note 20
Display:6.1 inch
=================================
=================================
Phone Name: Iphone 12 Pro
Display:6.2 inch
“Ram”:6 Gb”
=================================
Phone Name: Iphone 12 Pro
Display:6.2 inch,Amoled panel
“Ram”:6 Gb”
Ram:DDR5
=================================

In [ ]:
#task 6 
class Student:
  total=0
  bba_total=0
  cse_total=0
  def __init__(self,name,dep):
    self.name=name
    self.dep=dep
    Student.total+=1
    print("Creating Student Number: ",Student.total)
    if dep=="BBA":
      Student.bba_total+=1
    else:
      Student.cse_total+=1
  
  def individualInfo(self):
    print(f"{self.name} is from {self.dep} department.")
    print(f"Serial of {self.name} among all students' is: {Student.total}")
    if self.dep=="BBA":
      print(f"Serial of {self.name} in BBA department is: {Student.bba_total}")
    else:
      print(f"Serial of {self.name} in CSE department is: {Student.cse_total}")

  def totalInfo(self):
    print("Total Number of Student: ",Student.total)
    print("Total Number of CSE Student: ",Student.cse_total)
    print("Total Number of BBA Student: ",Student.bba_total)


s1 = Student("Naruto", "CSE")
print('----------------------')
s1.individualInfo()
print('#############################')
s1.totalInfo()
print('============================')
 
s2 = Student("Sakura", "BBA")
print('----------------------')
s2.individualInfo()
print('#############################')
s2.totalInfo()
print('============================')
 
s3 = Student("Shikamaru", "CSE")
print('----------------------')
s3.individualInfo()
print('#############################')
s3.totalInfo()
print('============================')
 
s4 = Student("Deidara", "BBA")
print('----------------------')
s4.individualInfo()
print('#############################')
s4.totalInfo()

Creating Student Number:  1
----------------------
Naruto is from CSE department.
Serial of Naruto among all students' is: 1
Serial of Naruto in CSE department is: 1
#############################
Total Number of Student:  1
Total Number of CSE Student:  1
Total Number of BBA Student:  0
============================
Creating Student Number:  2
----------------------
Sakura is from BBA department.
Serial of Sakura among all students' is: 2
Serial of Sakura in BBA department is: 1
#############################
Total Number of Student:  2
Total Number of CSE Student:  1
Total Number of BBA Student:  1
============================
Creating Student Number:  3
----------------------
Shikamaru is from CSE department.
Serial of Shikamaru among all students' is: 3
Serial of Shikamaru in CSE department is: 2
#############################
Total Number of Student:  3
Total Number of CSE Student:  2
Total Number of BBA Student:  1
============================
Creating Student Number:  4
----------------------
Deidara is from BBA department.
Serial of Deidara among all students' is: 4
Serial of Deidara in BBA department is: 2
#############################
Total Number of Student:  4
Total Number of CSE Student:  2
Total Number of BBA Student:  2

In [ ]:
#TASK 7 
class book:
    def __init__(self, name):
        self.name = name
        self.genre='biography'
    def review(self):
         print('This book is just out of the world,mind-blowing!')

class fiction(book):
  def __init__(self,name,genre=None):
    super().__init__(name)
    self.genre=genre
  
  def review(self):
    print(f"{self.name} which is a {self.genre} is just out of the world, mind-blowing!")

class nonfiction(book):
  def review(self):
    print(f"{self.name} which is a {self.genre} is just out of the world, mind-blowing!")

b1 = fiction("The Shining","Psychological horror")
b2 = nonfiction('A Beautiful Mind')
b1.review()
print('=========================')
b2.review()
print('=========================')

The Shining which is a Psychological horror is just out of the world, mind-blowing!
=========================
A Beautiful Mind which is a biography is just out of the world, mind-blowing!
=========================

In [ ]:
# task 8
class Processor:
    def __init__(self, model, thread, core):
        self.model = model
        self.core = core
        self.thread = thread

    def getInfo(self):
        print (f'Model:{self.model}\nCores:{self.core}\nThreads:{self.thread}\nThreads:{self.price}')
        


class Intel(Processor):
    def __init__(self, model, thread, core, price):
        super().__init__(model, thread, core)
        self.price = price


class AMD(Processor):
    def __init__(self, model, thread, core, price):
        super().__init__(model, thread, core)
        self.price = price

    def getInfo(self):
        print (f'Model:{self.model}\nCores:{self.core}\nThreads:{self.thread}\nThreads:{self.price}')


# Write your code here
p1 = Intel("Intel i5 10th Gen", 6, 12, 17000)
p2 = AMD("Ryzen 5 3500X", 6, 6, 13800)
p3 = AMD("Ryzen 5 3600", 6, 12, 16900)
print('======================')
p1.getInfo()
print('======================')
p2.getInfo()
print('======================')
p3.getInfo()

======================
Model:Intel i5 10th Gen
Cores:12
Threads:6
Threads:17000
======================
Model:Ryzen 5 3500X
Cores:6
Threads:6
Threads:13800
======================
Model:Ryzen 5 3600
Cores:12
Threads:6
Threads:16900

In [ ]:
#task 9 #pr

class Fruit:


  Total_order=0
  
  def __init__(self, Order_ID, weight):
      self.Order_ID=Order_ID
      self.weight=weight

      Fruit.Total_order=Fruit.Total_order+1
      
  
  def __str__(self):
      return self.Order_ID+", Weight: "+str(self.weight)

  # def __add__(self,other):
  #   a=self.total_price+other.total_price
  #   return(f"The total Price of the orders are: {a}")

class Mango(Fruit):

  def __init__(self, Order_ID, weight,Variety,price):
    super().__init__(Order_ID, weight)
    self.variety=Variety
    self.price=price
    self.total_price=self.weight*self.price

  def __add__(self,other):
    a=self.total_price+other.total_price
    return(f"The total Price of the orders are: {a}")
    

  def __str__(self):
    return f"{self.Order_ID}, Weight: {self.weight} ,Variety: {self.variety}\n Toral price:{self.total_price}"

  def __add__(self,other):
    a=self.total_price+other.total_price
    return(f"The total Price of the orders are: {a}")




class JackFruit(Fruit):
  def __init__(self, Order_ID, weight,price):
    super().__init__(Order_ID, weight)
    self.price=price
    self.total_price=self.weight*self.price
    

  def __str__(self):
    return f"{self.Order_ID}, Weight: {self.weight}\n Toral price:{self.total_price}"
    
  def __add__(self,other):
    a=self.total_price+other.total_price
    return(f"The total Price of the orders are: {a}")

m1=Mango("Order Id 1", 5,"GopalVog",250)
print(m1)
m2=Mango("Order Id 2", 5,"HariVanga", 230)
print(m2) 
j1=JackFruit("Order Id 3", 5,250)
print(j1)
j2=JackFruit("Order Id 4", 4,210)
print(j2)
print("Total number of Orders: "+str(Fruit.Total_order))
print("==================")
print(m1+m2)
print("==================")
print(j1+j2)

Order Id 1, Weight: 5 ,Variety: GopalVog
 Toral price:1250
Order Id 2, Weight: 5 ,Variety: HariVanga
 Toral price:1150
Order Id 3, Weight: 5
 Toral price:1250
Order Id 4, Weight: 4
 Toral price:840
Total number of Orders: 4
==================
The total Price of the orders are: 2400
==================
The total Price of the orders are: 2090

In [ ]:
#task 10 
class Student:
    def __init__(self,name,ID):
        self.name = name
        self.ID = ID
    def Details(self):
        return "Name: "+self.name+"\n"+"ID: "+self.ID+"\n"

class CSEStudent(Student):
  def __init__(self,name,id,semester):
    super().__init__(name,id)
    self.semester=semester
    self.course={}

  def Details(self):
    return(f"Name: {self.name}\nID: {self.ID}\nCurrent semester:{self.semester}")

  def addCourseWithMarks(self,*n):
    n=list(n)
    for i in range(0,len(n),2):
      if n[i+1]>=85:
        self.course[n[i]]=4.0
      elif 80<=n[i+1]<=84:
        self.course[n[i]]=3.3
      elif 70<=n[i+1]<=79:
        self.course[n[i]]=3.0
      elif 65<=n[i+1]<=96:
        self.course[n[i]]=2.3
      elif 57<=n[i+1]<=64:
        self.course[n[i]]=2.0
      elif 55<=n[i+1]<=56:
        self.course[n[i]]=1.3
      elif 50<=n[i+1]<=54:
        self.course[n[i]]=1.00
      else:
        self.course[n[i]]=0.00
      

   

  def showGPA(self):
    print(f"{self.name} has taken {len(self.course)} courses.")
    
    sum=0
    for key,value in self.course.items():
      print(f"{key}: {value}")
      sum+=(int(value)*3)
    gpa=(sum/(len(self.course)*3))

    
    print(f"GPA of Carol is: {gpa:.2f}")


    
    

    
    


Bob = CSEStudent("Bob","20301018",'Fall 2020')
Carol = CSEStudent("Carol","16301814",'Fall 2020')
Anny = CSEStudent("Anny","18201234",'Fall 2020')
print("#########################")
print(Bob.Details())
print("#########################")
print(Carol.Details())
print("#########################")
print(Anny.Details())
print("#########################")
Bob.addCourseWithMarks("CSE111",83.5,"CSE230",73.0,"CSE260",92.5)
Carol.addCourseWithMarks("CSE470",62.5,"CSE422",69.0,"CSE460",76.5,"CSE461",87.0)
Anny.addCourseWithMarks("CSE340",45.5,"CSE321",95.0,"CSE370",91.0)
print("----------------------------")
Bob.showGPA()
print("----------------------------")
Carol.showGPA()
print("----------------------------")
Anny.showGPA()

#########################
Name: Bob
ID: 20301018
Current semester:Fall 2020
#########################
Name: Carol
ID: 16301814
Current semester:Fall 2020
#########################
Name: Anny
ID: 18201234
Current semester:Fall 2020
#########################
----------------------------
Bob has taken 3 courses.
CSE111: 3.3
CSE230: 3.0
CSE260: 4.0
GPA of Carol is: 3.33
----------------------------
Carol has taken 4 courses.
CSE470: 2.0
CSE422: 2.3
CSE460: 3.0
CSE461: 4.0
GPA of Carol is: 2.75
----------------------------
Anny has taken 3 courses.
CSE340: 0.0
CSE321: 4.0
CSE370: 4.0
GPA of Carol is: 2.67

In [ ]:
##task 11

class Transport:
    total_traveller = 0
    
    def __init__(self, name, fare):
        self.name = name
        self.baseFare = fare
    
    def __str__(self):
        s = 'Name: '+self.name+', Base fare: '+str(self.baseFare)
        return s


class Bus(Transport):
  def __init__(self, name,fare):
    super().__init__(name,fare)
    self.passenger={}
  def addPassengerWithBags(self,*n):
    for i in range(0,len(n),2):
      self.passenger[n[i]]=n[i+1]
    Transport.total_traveller+=len(self.passenger)


  def __str__(self):
    a=""
    for key,value in self.passenger.items():
      if value<=2:
        a+=f"Name: {key}, Fare: {self.baseFare}\n"
      elif 3<=value<=5:
        a+=f"Name: {key}, Fare: {self.baseFare+60}\n"
      else:
        a+=f"Name: {key}, Fare: {self.baseFare+105}\n"
    total_passenger=len(self.passenger)
    return f"Name: {self.name}, Base fare: {self.baseFare} \nTotal Passenger(s): {total_passenger}\nPassenger details:\n{a}"

class Train(Transport):
  def __init__(self, name,fare):
    super().__init__(name,fare)
    self.passenger={}
  def addPassengerWithBags(self,*n):
    for i in range(0,len(n),2):
      self.passenger[n[i]]=n[i+1]
    Transport.total_traveller+=len(self.passenger)

  def __str__(self):
    a=""
    for key,value in self.passenger.items():
      if value<=2:
        a+=f"Name: {key}, Fare: {self.baseFare}\n"
      elif 3<=value<=5:
        a+=f"Name: {key}, Fare: {self.baseFare+60}\n"
      else:
        a+=f"Name: {key}, Fare: {self.baseFare+105}\n"
    total_passenger=len(self.passenger)
    return f"Name: {self.name}, Base fare: {self.baseFare} \nTotal Passenger(s): {total_passenger}\nPassenger details:\n{a}"






t1 = Bus('Volvo', 950)
print("=================================")
t1.addPassengerWithBags('David', 6,  'Mike', 1, 'Carol', 3)
print("=================================")
print(t1)
print("=================================")
t2 = Train('Silk City', 850)
print("=================================")
t2.addPassengerWithBags('Bob', 2, 'Simon', 4)
print("=================================")
print(t2)
print("=================================")
print('Total Passengers in Transport: ', Transport.total_traveller )

=================================
=================================
Name: Volvo, Base fare: 950
Total Passenger(s): 3
Passenger details:
Name: David, Fare: 1055
Name: Mike, Fare: 950
Name: Carol, Fare: 1010

=================================
=================================
=================================
Name: Silk City, Base fare: 850
Total Passenger(s): 2
Passenger details:
Name: Bob, Fare: 850
Name: Simon, Fare: 910

=================================
Total Passengers in Transport:  5

In [ ]:
# task 12 #add hoitese nh

class AppleProduct:
  def __init__(self, name, model, base_price):
    self.name = name
    self.model = model
    self.base_price = base_price
  def companyInfo(self):
    st = ("Company Name: Apple\nFouder: Steve Jobs, Steve Wozniak, Ronald Wayne\nCurrent CEO: Tim Cook\nAddress: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States")
    return st
  def feature(self):
    st = (f"Name: {self.name}\nProduct Model: {self.model}\nHardware Quality: Excellent Hardwares\nGuarantee/ Warranty: Apple Care")
    return st
  def __str__(self):
    print('This is apple product.')
  def calculatePrice(self):
    print('Total Price:', self.base_price)

    # def __add__(self,other):
    #   return(self.changed_price+other.changed_price)


class MacBookPro2020(AppleProduct):
    def __init__(self, name, model, ram, chip, tax):
        super().__init__(name, model, base_price=1299)
        self.ram = ram
        self.chip = chip
        self.tax = tax
        self.changed_price = 0

    def __str__(self):
        a = super().companyInfo()
        b = super().feature()
        # return(f"Product Details:\nName:{self.name}\nProduct Model:{self.model}\nHardware Quality: Excellent Hardwares \nGuarantee/ Warranty: Apple Care\nRAM: {self.ram}\nChip: {self.chip}\nCompany Details:\n{a} ")
        return (f"{a}\n{b}")

    def calculatePrice(self):
        print("Calculating Total Price:")
        print("Base Price:", self.base_price)
        print("Tax:", self.tax)
        self.changed_price = (self.base_price + ((self.tax / 100) * self.base_price))
        print("Total price", self.changed_price)

    def __add__(self, other):
        a = self.changed_price + other.changed_price
        return a


class iPhone12(AppleProduct):
    def __init__(self, name, model, ram, chip, tax):
        super().__init__(name, model, base_price=799)
        self.ram = ram
        self.chip = chip
        self.tax = tax
        self.changed_price = 0

    def __str__(self):
        a = super().companyInfo()
        b = super().feature()
        # return(f"Product Details:\nName:{self.name}\nProduct Model:{self.model}\nHardware Quality: Excellent Hardwares \nGuarantee/ Warranty: Apple Care\nRAM: {self.ram}\nChip: {self.chip}\nCompany Details:\n{a} ")
        return (f"{a}\n{b}")

    def calculatePrice(self):
        print("Calculating Total Price:")
        print("Base Price:", self.base_price)
        print("Tax:", self.tax)
        self.changed_price = (self.base_price + ((self.tax / 100) * self.base_price))
        print("Total price", self.changed_price)

    # def __add__(self, other):
    #   a=self.changed_price+other.changed_price
    #   return  a


# Write your codes here.
# Do not change the following lines of code.


m1 = MacBookPro2020('MacBook', 'MacBookPro2020', 8, 'M1', 10)
print(m1)
print('====================================')
m1.calculatePrice()
print('###################################')
iphone = iPhone12('iPhone', 'iPhone 12', 8, 'A14', 5)
print(iphone)
print('====================================')
iphone.calculatePrice()
print('###################################')
print('Total Price of these two products: ', end='')
print('%.2f Dollars' % (m1 + iphone))

Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
Name: MacBook
Product Model: MacBookPro2020
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
====================================
Calculating Total Price:
Base Price: 1299
Tax: 10
Total price 1428.9
###################################
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
Name: iPhone
Product Model: iPhone 12
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
====================================
Calculating Total Price:
Base Price: 799
Tax: 5
Total price 838.95
###################################
Total Price of these two products: 2267.85 Dollars

In [ ]:
# TASK 13
class University:
    name = "ABC University"
    numberOfStudents = 0
    admissionFee = 28000
    Library = 2000

    def __init__(self, n, i):
        self.stName = n
        self.stId = i


    def payment(self):
        return self.admissionFee + self.Library

    def __str__(self):
        return "Student Name: {}, ID: {}\nFee: {}".format(self.stName, self.stId, self.payment())


# Write your codes here.
class CSE_dept(University):

    PerCreditFee = 6600
    SemesterFee = 7700
    LabFee = 2750

    def __init__(self, name, id, credit=6):
        super().__init__(name, id)
        self.credit = credit
        
        
        
        

        University.numberOfStudents+=1



    def __str__(self):
        self.total_fee = (super().payment() + self.SemesterFee + (self.credit * self.PerCreditFee)+self.LabFee)
        return (f"Student Name: {self.stName}, ID: {self.stId}\nFee: {self.total_fee}")

    def payment_details(self):
        print("DETAILS:")
        print("Admission Fee: ",University.admissionFee)
        print("Library Fee: ",University.Library)
        print("Semester Fee: ",self.SemesterFee)
        print("Per Credit Fee: ",self.PerCreditFee)
        print("Number of credits:",self.credit)
        print("Lab Fee:",self.LabFee)

    def __add__(self,other):
      return(self.total_fee+other.total_fee)

class PHR_dept(University):

    PerCreditFee = 6600
    SemesterFee = 11000

    def __init__(self, name, id, credit=9):
        super().__init__(name, id)
        self.credit = credit
        
        

        

        University.numberOfStudents+=1



    def __str__(self):
        self.total_fee = (super().payment() + self.SemesterFee + (self.credit * self.PerCreditFee))
        return (f"Student Name: {self.stName}, ID: {self.stId}\nFee: {self.total_fee}")

    def payment_details(self):
        print("DETAILS:")
        print("Admission Fee: ",University.admissionFee)
        print("Library Fee: ",University.Library)
        print("Semester Fee: ",self.SemesterFee)
        print("Per Credit Fee: ",self.PerCreditFee)
        print("Number of credits:",self.credit)

    def __add__(self,other):
      return(self.total_fee+other.total_fee)

# Do not change the following lines of code.

c1 = CSE_dept("Mary", "5678")
print(c1)
c1.payment_details()
print("===========================")
p1 = PHR_dept("Simon", "91011")
print(p1)
p1.payment_details()
print("===========================")
c2 = CSE_dept("Adam", "1234", 12)
print(c2)
c2.payment_details()
print("===========================")
p2 = PHR_dept("David", "121314", 15)
print(p2)
p2.payment_details()
print("===========================")
print("Total Number of Students:", University.numberOfStudents)
print("Total University Revenue:", (c1 + c2) + (p1 + p2))
print("===========================")
print("Due to the pandemic, admission and library fees have been reduced for all departments. ")
University.admissionFee -= 1000
University.Library -= 100
print("The credit, semester and lab fees have been reduced for the CSE department. ")
CSE_dept.PerCreditFee -= 100
CSE_dept.SemesterFee -= 100
CSE_dept.LabFee -= 100
print("The credit and semester fees have been reduced for the PHR department.\n ")
PHR_dept.PerCreditFee -= 100
PHR_dept.SemesterFee -= 1000
print(c1)
print(p1)
print(c2)
print(p2)
print("===========================")
print("Total Number of Students:", University.numberOfStudents)
print("Total University Revenue:", (c1 + c2) + (p1 + p2))

Student Name: Mary, ID: 5678
Fee: 80050
DETAILS:
Admission Fee:  28000
Library Fee:  2000
Semester Fee:  7700
Per Credit Fee:  6600
Number of credits: 6
Lab Fee: 2750
===========================
Student Name: Simon, ID: 91011
Fee: 100400
DETAILS:
Admission Fee:  28000
Library Fee:  2000
Semester Fee:  11000
Per Credit Fee:  6600
Number of credits: 9
===========================
Student Name: Adam, ID: 1234
Fee: 119650
DETAILS:
Admission Fee:  28000
Library Fee:  2000
Semester Fee:  7700
Per Credit Fee:  6600
Number of credits: 12
Lab Fee: 2750
===========================
Student Name: David, ID: 121314
Fee: 140000
DETAILS:
Admission Fee:  28000
Library Fee:  2000
Semester Fee:  11000
Per Credit Fee:  6600
Number of credits: 15
===========================
Total Number of Students: 4
Total University Revenue: 440100
===========================
Due to the pandemic, admission and library fees have been reduced for all departments.
The credit, semester and lab fees have been reduced for the CSE department.
The credit and semester fees have been reduced for the PHR department.

Student Name: Mary, ID: 5678
Fee: 78150
Student Name: Simon, ID: 91011
Fee: 97400
Student Name: Adam, ID: 1234
Fee: 117150
Student Name: David, ID: 121314
Fee: 136400
===========================
Total Number of Students: 4
Total University Revenue: 429100

In [ ]:
#TASK 14 

class Library:
    Total_book = 1000
    borrow_data = {}

    def __init__(self, n, id):
        self.student_name = n
        self.student_id = id

    def borrowbook(self):
        print("A book is borrowed!")

    def __str__(self):
        return "Library: XYZ"


class Student(Library):
    def __init__(self,name,id):
        super().__init__(name,id)
        self.book_name=""
        self.book_uni_id=""


    def borrowbook(self,b_name,b_code=None):
        self.book_name = b_name
        self.book_uni_id=b_code

        Student.Total_book-=1
        Library.borrow_data[self.book_name]=[self.student_name]

        a=super().borrowbook()
        b=f"Number of books available for borrowing = {Student.Total_book}"
        if self.book_uni_id!=None:
            c=f"{self.book_name} book with the unique id {self.book_uni_id} is borrowed by {self.student_name}({self.student_id}\n{b}) "
        else:
            c=f"{self.book_name} book is borrowed by {self.student_name}({self.student_id}\n{b}) "

        print (f'{a}\n{c}')

    def returnAllBooks(self):
      for key,value in Library.borrow_data.items():
        if self.student_name in value:
          value.remove(self.student_name)
          

        


        

# Write your code here
s1 = Student("Alice", 18101259)
s1.borrowbook("The Alchemist", "Hdw652")
print("===============")
print(s1)
print("===============")
print(Library.borrow_data)
print("===============")
s1.borrowbook("Wuthering Heights")
print("===============")
print(s1)
print("===============")
s2 = Student("David", 18141777)
s2.borrowbook("The Alchemist", "Hdw652")
print("===============")
s2.borrowbook("The Vampyre")
print("===============")
print(Library.borrow_data)
print("===============")
s1.returnAllBooks()
print("===============")
print(Library.borrow_data)

A book is borrowed!
None
The Alchemist book with the unique id Hdw652 is borrowed by Alice(18101259
Number of books available for borrowing = 999)
===============
Library: XYZ
===============
{'The Alchemist': ['Alice']}
===============
A book is borrowed!
None
Wuthering Heights book is borrowed by Alice(18101259
Number of books available for borrowing = 998)
===============
Library: XYZ
===============
A book is borrowed!
None
The Alchemist book with the unique id Hdw652 is borrowed by David(18141777
Number of books available for borrowing = 997)
===============
A book is borrowed!
None
The Vampyre book is borrowed by David(18141777
Number of books available for borrowing = 996)
===============
{'The Alchemist': ['David'], 'Wuthering Heights': ['Alice'], 'The Vampyre': ['David']}
===============
===============
{'The Alchemist': ['David'], 'Wuthering Heights': [], 'The Vampyre': ['David']}

In [ ]:
#task 14

class Library:
    Total_book = 1000
    borrow_data = {}

    def __init__(self, n, id):
        self.student_name = n
        self.student_id = id

    def borrowbook(self):
        print("A book is borrowed!")

    def __str__(self):
        return "Library: XYZ"


class Student(Library):
    def __init__(self,name,id):
        super().__init__(name,id)
        self.book_name=""
        self.book_uni_id=""


    def borrowbook(self,b_name,b_code=None):
        self.book_name = b_name
        self.book_uni_id=b_code

        Library.borrow_data[self.book_name]=[self.student_name]

        Student.Total_book-=1

        a=super().borrowbook()
        c=f"Number of books available for borrowing = ({Student.Total_book})"
        if self.book_uni_id!=None:
            b=f"{self.book_name} book with the unique id {self.book_uni_id} is borrowed by {self.student_name}({self.student_id})\n{c} "
        else:
            b=f"{self.book_name} book is borrowed by {self.student_name}({self.student_id}\n{c} "

        print (f'{a}\n{b}')

    def __str__(self):
        a=super().__str__()
        b=f"Student Name: {self.student_name} ID: {self.student_id}"
        c=f"Books borrowed: {self.book_name} "
        return f"{a}\n{b}\n{c}"

    def returnAllBooks(self):
        print(f"All Books are returned by {self.student_name}.")

        for key ,value in Student.borrow_data.items():
            if self.book_name in Student.borrow_data.keys():
                Student.borrow_data.pop(key)


    


# Write your code here
s1 = Student("Alice", 18101259)
s1.borrowbook("The Alchemist", "Hdw652")
print("===============")
print(s1)
print("===============")
print(Library.borrow_data)
print("===============")
s1.borrowbook("Wuthering Heights")
print("===============")
print(s1)
print("===============")
s2 = Student("David", 18141777)
s2.borrowbook("The Alchemist", "Hdw652")
print("===============")
s2.borrowbook("The Vampyre")
print("===============")
print(Library.borrow_data)
print("===============")
s1.returnAllBooks()
print("===============")
print(Library.borrow_data)

A book is borrowed!
None
The Alchemist book with the unique id Hdw652 is borrowed by Alice(18101259)
Number of books available for borrowing = (999)
===============
Library: XYZ
Student Name: Alice ID: 18101259
Books borrowed: The Alchemist
===============
{'The Alchemist': ['Alice']}
===============
A book is borrowed!
None
Wuthering Heights book is borrowed by Alice(18101259
Number of books available for borrowing = (998)
===============
Library: XYZ
Student Name: Alice ID: 18101259
Books borrowed: Wuthering Heights
===============
A book is borrowed!
None
The Alchemist book with the unique id Hdw652 is borrowed by David(18141777)
Number of books available for borrowing = (997)
===============
A book is borrowed!
None
The Vampyre book is borrowed by David(18141777
Number of books available for borrowing = (996)
===============
{'The Alchemist': ['David'], 'Wuthering Heights': ['Alice'], 'The Vampyre': ['David']}
===============
All Books are returned by Alice.

RuntimeError: ignored

In [ ]:
#task 15
class Player:
    database={}
    playerNo = 0
    def __init__(self,name,team,jerseyNo):
        self.name = name
        self.team = team
        self.jerseyNo = jerseyNo
    def __str__(self):
        return "Name:{}\nTeam:{}\nJersey No:{}".format(self.name,self.team,self.jerseyNo)

#Write your code here
class FootballPlayer(Player):
  def __init__(self,name,team,jersy,goal,date="Not yet retired"):
    super().__init__(name,team,jersy)
    self.goal=goal
    self.date=date
    Player.playerNo+=1
    a,b=self.name.split(" ")
    self.id=str(Player.playerNo)+a[0]+b[0]+str(self.jerseyNo)
    print(self.id)
    Player.database[self.id]=[self.name,self.team,self.jerseyNo,self.goal,self.date]
    print(Player.database)
    
  @classmethod
  def createPlayer(cls,name,team,jersy,goal,date):
    p=FootballPlayer(name,team,jersy,goal,date)
    return p
    

    
  

print("Number of players:",Player.playerNo)
print("Player Database:",Player.database)
print("#################################")
p1 = FootballPlayer("Lionel Messi","Barcelona",10,231)
print("------Details of the player------")
print(p1)
print("#################################")
p2 = FootballPlayer("Cristiano Ronaldo","Juventus",7,215)
print("------Details of the player------")
print(p2)
print("#################################")
p3 = FootballPlayer.createPlayer("Miroslav Klose","Lazio",11,71,"11 Aug,2014")
print("------Details of the player------")
print(p3)
print("#################################")
print("Number of players:",Player.playerNo)
print("Player Database:",Player.database)

Number of players: 0
Player Database: {}
#################################
1LM10
{'1LM10': ['Lionel Messi', 'Barcelona', 10, 231, 'Not yet retired']}
------Details of the player------
Name:Lionel Messi
Team:Barcelona
Jersey No:10
#################################
2CR7
{'1LM10': ['Lionel Messi', 'Barcelona', 10, 231, 'Not yet retired'], '2CR7': ['Cristiano Ronaldo', 'Juventus', 7, 215, 'Not yet retired']}
------Details of the player------
Name:Cristiano Ronaldo
Team:Juventus
Jersey No:7
#################################
3MK11
{'1LM10': ['Lionel Messi', 'Barcelona', 10, 231, 'Not yet retired'], '2CR7': ['Cristiano Ronaldo', 'Juventus', 7, 215, 'Not yet retired'], '3MK11': ['Miroslav Klose', 'Lazio', 11, 71, '11 Aug,2014']}
------Details of the player------
Name:Miroslav Klose
Team:Lazio
Jersey No:11
#################################
Number of players: 3
Player Database: {'1LM10': ['Lionel Messi', 'Barcelona', 10, 231, 'Not yet retired'], '2CR7': ['Cristiano Ronaldo', 'Juventus', 7, 215, 'Not yet retired'], '3MK11': ['Miroslav Klose', 'Lazio', 11, 71, '11 Aug,2014']}